// generated by alap_gen_ng.

use std::{fs::File, io::Read, str::FromStr};

use crate::{
    attributes::*, grammar::Specification, production::ProductionTail, symbol::tag::TagOrToken,
    symbol::Associativity,
};

use lazy_static::lazy_static;

use std::collections::BTreeSet;

macro_rules! btree_set {
    () => { BTreeSet::new() };
    ( $( $x:expr ),* ) => {
        {
            let mut set = BTreeSet::new();
            $( set.insert($x); )*
            set
        }
    };
    ( $( $x:expr ),+ , ) => {
        btree_set![ $( $x ), * ]
    };
}

use lalr1_plus;
use lexan;

#[derive(Debug, Clone, Copy, PartialOrd, Ord, PartialEq, Eq)]
pub enum AATerminal {
    AAEnd,
    ACTION,
    ATTR,
    COLON,
    DOT,
    ERROR,
    IDENT,
    INJECT,
    LEFT,
    LITERAL,
    NEWSECTION,
    NONASSOC,
    NUMBER,
    PRECEDENCE,
    PREDICATE,
    REGEX,
    RIGHT,
    RR,
    RUSTCODE,
    SKIP,
    SR,
    TARGET,
    TOKEN,
    VBAR,
}

impl std::fmt::Display for AATerminal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            AATerminal::AAEnd => write!(f, r###"AAEnd"###),
            AATerminal::ACTION => write!(f, r###"ACTION"###),
            AATerminal::ATTR => write!(f, r###""%attr""###),
            AATerminal::COLON => write!(f, r###"":""###),
            AATerminal::DOT => write!(f, r###"".""###),
            AATerminal::ERROR => write!(f, r###""%error""###),
            AATerminal::IDENT => write!(f, r###"IDENT"###),
            AATerminal::INJECT => write!(f, r###""%inject""###),
            AATerminal::LEFT => write!(f, r###""%left""###),
            AATerminal::LITERAL => write!(f, r###"LITERAL"###),
            AATerminal::NEWSECTION => write!(f, r###""%%""###),
            AATerminal::NONASSOC => write!(f, r###""%nonassoc""###),
            AATerminal::NUMBER => write!(f, r###"NUMBER"###),
            AATerminal::PRECEDENCE => write!(f, r###""%prec""###),
            AATerminal::PREDICATE => write!(f, r###"PREDICATE"###),
            AATerminal::REGEX => write!(f, r###"REGEX"###),
            AATerminal::RIGHT => write!(f, r###""%right""###),
            AATerminal::RR => write!(f, r###""%reduce_reduce""###),
            AATerminal::RUSTCODE => write!(f, r###"RUSTCODE"###),
            AATerminal::SKIP => write!(f, r###""%skip""###),
            AATerminal::SR => write!(f, r###""%shift_reduce""###),
            AATerminal::TARGET => write!(f, r###""%target""###),
            AATerminal::TOKEN => write!(f, r###""%token""###),
            AATerminal::VBAR => write!(f, r###""|""###),
        }
    }
}

lazy_static! {
    static ref AALEXAN: lexan::LexicalAnalyzer<AATerminal> = {
        use AATerminal::*;
        lexan::LexicalAnalyzer::new(
            &[
                (NEWSECTION, r###"%%"###),
                (ATTR, r###"%attr"###),
                (ERROR, r###"%error"###),
                (INJECT, r###"%inject"###),
                (LEFT, r###"%left"###),
                (NONASSOC, r###"%nonassoc"###),
                (PRECEDENCE, r###"%prec"###),
                (RR, r###"%reduce_reduce"###),
                (RIGHT, r###"%right"###),
                (SR, r###"%shift_reduce"###),
                (SKIP, r###"%skip"###),
                (TARGET, r###"%target"###),
                (TOKEN, r###"%token"###),
                (DOT, r###"."###),
                (COLON, r###":"###),
                (VBAR, r###"|"###),
            ],
            &[
                (ACTION, r###"(!\{(.|[\n\r])*?!\})"###),
                (LITERAL, r###"("(\\"|[^"\t\r\n\v\f])*")"###),
                (RUSTCODE, r###"(%\{(.|[\n\r])*?%\})"###),
                (NUMBER, r###"([0-9]+)"###),
                (IDENT, r###"([a-zA-Z]+[a-zA-Z0-9_]*)"###),
                (REGEX, r###"(\(.+\))"###),
                (PREDICATE, r###"(\?\((.|[\n\r])*?\?\))"###),
            ],
            &[
                r###"(/\*(.|[\n\r])*?\*/)"###,
                r###"(//[^\n\r]*)"###,
                r###"(\s+)"###,
            ],
            AAEnd,
        )
    };
}

#[derive(Debug, Clone, Copy, PartialOrd, Ord, PartialEq, Eq)]
pub enum AANonTerminal {
    AAStart,
    Action,
    AttributeType,
    Configuration,
    Definitions,
    ExpectedConflicts,
    ExpectedRRConflicts,
    ExpectedSRConflicts,
    Injection,
    InjectionHead,
    NewTokenName,
    Number,
    OptionalInjection,
    Preamble,
    PrecedenceDefinition,
    PrecedenceDefinitions,
    Predicate,
    ProductionGroup,
    ProductionGroupHead,
    ProductionRules,
    ProductionTail,
    ProductionTailList,
    RegEx,
    SkipDefinition,
    SkipDefinitions,
    Specification,
    Symbol,
    SymbolList,
    Tag,
    TagList,
    TaggedPrecedence,
    TargetType,
    TokenDefinition,
    TokenDefinitions,
}

impl std::fmt::Display for AANonTerminal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            AANonTerminal::AAStart => write!(f, r"AAStart"),
            AANonTerminal::Action => write!(f, r"Action"),
            AANonTerminal::AttributeType => write!(f, r"AttributeType"),
            AANonTerminal::Configuration => write!(f, r"Configuration"),
            AANonTerminal::Definitions => write!(f, r"Definitions"),
            AANonTerminal::ExpectedConflicts => write!(f, r"ExpectedConflicts"),
            AANonTerminal::ExpectedRRConflicts => write!(f, r"ExpectedRRConflicts"),
            AANonTerminal::ExpectedSRConflicts => write!(f, r"ExpectedSRConflicts"),
            AANonTerminal::Injection => write!(f, r"Injection"),
            AANonTerminal::InjectionHead => write!(f, r"InjectionHead"),
            AANonTerminal::NewTokenName => write!(f, r"NewTokenName"),
            AANonTerminal::Number => write!(f, r"Number"),
            AANonTerminal::OptionalInjection => write!(f, r"OptionalInjection"),
            AANonTerminal::Preamble => write!(f, r"Preamble"),
            AANonTerminal::PrecedenceDefinition => write!(f, r"PrecedenceDefinition"),
            AANonTerminal::PrecedenceDefinitions => write!(f, r"PrecedenceDefinitions"),
            AANonTerminal::Predicate => write!(f, r"Predicate"),
            AANonTerminal::ProductionGroup => write!(f, r"ProductionGroup"),
            AANonTerminal::ProductionGroupHead => write!(f, r"ProductionGroupHead"),
            AANonTerminal::ProductionRules => write!(f, r"ProductionRules"),
            AANonTerminal::ProductionTail => write!(f, r"ProductionTail"),
            AANonTerminal::ProductionTailList => write!(f, r"ProductionTailList"),
            AANonTerminal::RegEx => write!(f, r"RegEx"),
            AANonTerminal::SkipDefinition => write!(f, r"SkipDefinition"),
            AANonTerminal::SkipDefinitions => write!(f, r"SkipDefinitions"),
            AANonTerminal::Specification => write!(f, r"Specification"),
            AANonTerminal::Symbol => write!(f, r"Symbol"),
            AANonTerminal::SymbolList => write!(f, r"SymbolList"),
            AANonTerminal::Tag => write!(f, r"Tag"),
            AANonTerminal::TagList => write!(f, r"TagList"),
            AANonTerminal::TaggedPrecedence => write!(f, r"TaggedPrecedence"),
            AANonTerminal::TargetType => write!(f, r"TargetType"),
            AANonTerminal::TokenDefinition => write!(f, r"TokenDefinition"),
            AANonTerminal::TokenDefinitions => write!(f, r"TokenDefinitions"),
        }
    }
}

impl lalr1_plus::Parser<AATerminal, AANonTerminal, AttributeData> for Specification {
    fn lexical_analyzer(&self) -> &lexan::LexicalAnalyzer<AATerminal> {
        &AALEXAN
    }

    fn viable_error_recovery_states(token: &AATerminal) -> BTreeSet<u32> {
        match token {
            _ => btree_set![],
        }
    }

    fn error_goto_state(state: u32) -> u32 {
        match state {
            _ => panic!("No error go to state for {}", state),
        }
    }

    fn look_ahead_set(state: u32) -> BTreeSet<AATerminal> {
        use AATerminal::*;
        return match state {
            0 => btree_set![ATTR, INJECT, TARGET, RUSTCODE],
            1 => btree_set![AAEnd],
            2 => btree_set![ATTR, TARGET],
            3 => btree_set![
                ATTR, INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, RR, SKIP, SR, TARGET, TOKEN,
                IDENT, RUSTCODE, AAEnd
            ],
            4 => btree_set![LITERAL],
            5 => btree_set![DOT],
            6 => btree_set![RUSTCODE],
            7 => btree_set![NEWSECTION],
            8 => btree_set![INJECT, TARGET],
            9 => btree_set![ATTR, INJECT],
            10 => btree_set![IDENT],
            11 => btree_set![IDENT],
            12 => btree_set![DOT],
            13 => btree_set![
                ATTR, INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, RR, SKIP, SR, TARGET, TOKEN,
                IDENT, RUSTCODE, AAEnd
            ],
            14 => btree_set![ATTR, INJECT, TARGET],
            15 => btree_set![INJECT, TOKEN],
            16 => btree_set![TARGET],
            17 => btree_set![ATTR],
            18 => btree_set![INJECT, NEWSECTION, RR, SR, TARGET],
            19 => btree_set![ATTR, INJECT, NEWSECTION, RR, SR],
            20 => btree_set![ATTR, TARGET],
            21 => btree_set![NEWSECTION],
            22 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, SKIP, TOKEN],
            23 => btree_set![TOKEN],
            24 => btree_set![INJECT, NEWSECTION, RR, SR],
            25 => btree_set![INJECT, NEWSECTION, RR, SR],
            26 => btree_set![INJECT, IDENT],
            27 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, SKIP],
            28 => btree_set![TOKEN],
            29 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, SKIP, TOKEN],
            30 => btree_set![IDENT],
            31 => btree_set![INJECT, NEWSECTION, RR, SR],
            32 => btree_set![INJECT, NEWSECTION, RR, SR],
            33 => btree_set![IDENT, AAEnd],
            34 => btree_set![IDENT],
            35 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT],
            36 => btree_set![SKIP],
            37 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, SKIP, TOKEN],
            38 => btree_set![LITERAL, REGEX],
            39 => btree_set![LITERAL, REGEX],
            40 => btree_set![INJECT, NEWSECTION],
            41 => btree_set![INJECT, NEWSECTION, SR],
            42 => btree_set![INJECT, NEWSECTION, RR],
            43 => btree_set![NUMBER],
            44 => btree_set![NUMBER],
            45 => btree_set![INJECT, NEWSECTION],
            46 => btree_set![INJECT, IDENT, AAEnd],
            47 => btree_set![DOT, ERROR, VBAR, ACTION, IDENT, LITERAL, PREDICATE],
            48 => btree_set![COLON],
            49 => btree_set![INJECT, IDENT, AAEnd],
            50 => btree_set![LEFT, NONASSOC, RIGHT],
            51 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, SKIP],
            52 => btree_set![REGEX],
            53 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, SKIP, TOKEN],
            54 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, SKIP, TOKEN],
            55 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, SKIP, TOKEN],
            56 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, SKIP, TOKEN],
            57 => btree_set![NEWSECTION],
            58 => btree_set![SR],
            59 => btree_set![RR],
            60 => btree_set![INJECT, NEWSECTION, SR],
            61 => btree_set![INJECT, NEWSECTION, RR, SR],
            62 => btree_set![INJECT, NEWSECTION, RR],
            63 => btree_set![NEWSECTION],
            64 => btree_set![IDENT, AAEnd],
            65 => btree_set![DOT, VBAR],
            66 => btree_set![DOT, VBAR],
            67 => btree_set![DOT, VBAR],
            68 => btree_set![DOT, VBAR, ACTION],
            69 => btree_set![DOT, ERROR, PRECEDENCE, VBAR, ACTION, IDENT, LITERAL, PREDICATE],
            70 => btree_set![DOT, VBAR],
            71 => btree_set![DOT, PRECEDENCE, VBAR, ACTION],
            72 => btree_set![DOT, ERROR, PRECEDENCE, VBAR, ACTION, IDENT, LITERAL, PREDICATE],
            73 => btree_set![DOT, ERROR, PRECEDENCE, VBAR, ACTION, IDENT, LITERAL, PREDICATE],
            74 => btree_set![DOT, ERROR, PRECEDENCE, VBAR, ACTION, IDENT, LITERAL, PREDICATE],
            75 => btree_set![DOT, ERROR, PRECEDENCE, VBAR, ACTION, IDENT, LITERAL, PREDICATE],
            76 => btree_set![DOT, ERROR, VBAR, ACTION, IDENT, LITERAL, PREDICATE],
            77 => btree_set![IDENT, AAEnd],
            78 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT],
            79 => btree_set![IDENT, LITERAL],
            80 => btree_set![IDENT, LITERAL],
            81 => btree_set![IDENT, LITERAL],
            82 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, SKIP],
            83 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, SKIP],
            84 => btree_set![INJECT, NEWSECTION],
            85 => btree_set![INJECT, NEWSECTION],
            86 => btree_set![INJECT, IDENT, AAEnd],
            87 => btree_set![DOT, ERROR, VBAR, ACTION, IDENT, LITERAL, PREDICATE],
            88 => btree_set![DOT, VBAR],
            89 => btree_set![DOT, PRECEDENCE, VBAR, ACTION],
            90 => btree_set![DOT, VBAR, ACTION],
            91 => btree_set![DOT, VBAR],
            92 => btree_set![IDENT, LITERAL],
            93 => btree_set![DOT, ERROR, PRECEDENCE, VBAR, ACTION, IDENT, LITERAL, PREDICATE],
            94 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT],
            95 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, IDENT, LITERAL],
            96 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, IDENT, LITERAL],
            97 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, IDENT, LITERAL],
            98 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, IDENT, LITERAL],
            99 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, IDENT, LITERAL],
            100 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, IDENT, LITERAL],
            101 => btree_set![DOT, VBAR],
            102 => btree_set![DOT, VBAR, ACTION],
            103 => btree_set![DOT, VBAR],
            104 => btree_set![DOT, VBAR],
            105 => btree_set![DOT, VBAR, ACTION],
            106 => btree_set![DOT, VBAR, ACTION],
            107 => btree_set![INJECT, LEFT, NEWSECTION, NONASSOC, RIGHT, IDENT, LITERAL],
            108 => btree_set![DOT, VBAR],
            _ => panic!("illegal state: {}", state),
        };
    }

    fn next_action(
        &self,
        aa_state: u32,
        aa_attributes: &lalr1_plus::ParseStack<AATerminal, AANonTerminal, AttributeData>,
        aa_token: &lexan::Token<AATerminal>,
    ) -> lalr1_plus::Action {
        use lalr1_plus::Action;
        use AATerminal::*;
        let aa_tag = *aa_token.tag();
        return match aa_state {
            0 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                RUSTCODE => Action::Reduce(2),
                // Preamble: <empty> #(NonAssoc, 0)
                ATTR | TARGET => Action::Reduce(6),
                _ => Action::SyntaxError,
            },
            1 => match aa_tag {
                // AAStart: Specification #(NonAssoc, 0)
                AAEnd => Action::Accept,
                _ => Action::SyntaxError,
            },
            2 => match aa_tag {
                ATTR => Action::Shift(10),
                TARGET => Action::Shift(11),
                _ => Action::SyntaxError,
            },
            3 => match aa_tag {
                // OptionalInjection: Injection #(NonAssoc, 0)
                ATTR | INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT | RR | SKIP | SR | TARGET
                | TOKEN | IDENT | RUSTCODE | AAEnd => Action::Reduce(3),
                _ => Action::SyntaxError,
            },
            4 => match aa_tag {
                LITERAL => Action::Shift(12),
                _ => Action::SyntaxError,
            },
            5 => match aa_tag {
                DOT => Action::Shift(13),
                _ => Action::SyntaxError,
            },
            6 => match aa_tag {
                RUSTCODE => Action::Shift(14),
                _ => Action::SyntaxError,
            },
            7 => match aa_tag {
                NEWSECTION => Action::Shift(15),
                _ => Action::SyntaxError,
            },
            8 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                TARGET => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            9 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                ATTR => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            10 => match aa_tag {
                IDENT => Action::Shift(18),
                _ => Action::SyntaxError,
            },
            11 => match aa_tag {
                IDENT => Action::Shift(19),
                _ => Action::SyntaxError,
            },
            12 => match aa_tag {
                // InjectionHead: "%inject" LITERAL #(Right, 1)
                DOT => Action::Reduce(4),
                _ => Action::SyntaxError,
            },
            13 => match aa_tag {
                // Injection: InjectionHead "." #(NonAssoc, 0)
                ATTR | INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT | RR | SKIP | SR | TARGET
                | TOKEN | IDENT | RUSTCODE | AAEnd => Action::Reduce(5),
                _ => Action::SyntaxError,
            },
            14 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                ATTR | TARGET => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            15 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                TOKEN => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            16 => match aa_tag {
                TARGET => Action::Shift(11),
                _ => Action::SyntaxError,
            },
            17 => match aa_tag {
                ATTR => Action::Shift(10),
                _ => Action::SyntaxError,
            },
            18 => match aa_tag {
                // AttributeType: "%attr" IDENT #(NonAssoc, 0)
                INJECT | NEWSECTION | RR | SR | TARGET => Action::Reduce(10),
                _ => Action::SyntaxError,
            },
            19 => match aa_tag {
                // TargetType: "%target" IDENT #(NonAssoc, 0)
                ATTR | INJECT | NEWSECTION | RR | SR => Action::Reduce(11),
                _ => Action::SyntaxError,
            },
            20 => match aa_tag {
                // Preamble: OptionalInjection RUSTCODE OptionalInjection #(NonAssoc, 0)
                ATTR | TARGET => Action::Reduce(7),
                _ => Action::SyntaxError,
            },
            21 => match aa_tag {
                NEWSECTION => Action::Shift(26),
                _ => Action::SyntaxError,
            },
            22 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                TOKEN => Action::Reduce(2),
                // SkipDefinitions: <empty> #(NonAssoc, 0)
                LEFT | NEWSECTION | NONASSOC | RIGHT | SKIP => Action::Reduce(28),
                _ => Action::SyntaxError,
            },
            23 => match aa_tag {
                TOKEN => Action::Shift(30),
                _ => Action::SyntaxError,
            },
            24 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                NEWSECTION | RR | SR => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            25 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                NEWSECTION | RR | SR => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            26 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                IDENT => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            27 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                SKIP => Action::Reduce(2),
                // PrecedenceDefinitions: <empty> #(NonAssoc, 0)
                LEFT | NEWSECTION | NONASSOC | RIGHT => Action::Reduce(31),
                _ => Action::SyntaxError,
            },
            28 => match aa_tag {
                TOKEN => Action::Shift(30),
                _ => Action::SyntaxError,
            },
            29 => match aa_tag {
                // TokenDefinitions: OptionalInjection TokenDefinition #(NonAssoc, 0)
                INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT | SKIP | TOKEN => Action::Reduce(21),
                _ => Action::SyntaxError,
            },
            30 => match aa_tag {
                IDENT => Action::Shift(39),
                _ => Action::SyntaxError,
            },
            31 => match aa_tag {
                RR => Action::Shift(43),
                SR => Action::Shift(44),
                // ExpectedConflicts: <empty> #(NonAssoc, 0)
                INJECT | NEWSECTION => Action::Reduce(12),
                _ => Action::SyntaxError,
            },
            32 => match aa_tag {
                RR => Action::Shift(43),
                SR => Action::Shift(44),
                // ExpectedConflicts: <empty> #(NonAssoc, 0)
                INJECT | NEWSECTION => Action::Reduce(12),
                _ => Action::SyntaxError,
            },
            33 => match aa_tag {
                IDENT => Action::Shift(48),
                // Specification: Preamble Configuration "%%" Definitions "%%" ProductionRules #(NonAssoc, 0)
                AAEnd => Action::Reduce(1),
                _ => Action::SyntaxError,
            },
            34 => match aa_tag {
                IDENT => Action::Shift(48),
                _ => Action::SyntaxError,
            },
            35 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                LEFT | NONASSOC | RIGHT => Action::Reduce(2),
                // Definitions: TokenDefinitions SkipDefinitions PrecedenceDefinitions #(NonAssoc, 0)
                NEWSECTION => Action::Reduce(20),
                _ => Action::SyntaxError,
            },
            36 => match aa_tag {
                SKIP => Action::Shift(52),
                _ => Action::SyntaxError,
            },
            37 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                LEFT | NEWSECTION | NONASSOC | RIGHT | SKIP | TOKEN => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            38 => match aa_tag {
                LITERAL => Action::Shift(54),
                REGEX => Action::Shift(56),
                _ => Action::SyntaxError,
            },
            39 => match aa_tag {
                LITERAL | REGEX => {
                    if !Self::is_allowable_name(aa_attributes.at_len_minus_n(1).matched_text()) {
                        // NewTokenName: IDENT #(NonAssoc, 0) ?( !Self::is_allowable_name($1.matched_text()) ?)
                        Action::Reduce(26)
                    } else {
                        // NewTokenName: IDENT #(NonAssoc, 0)
                        Action::Reduce(27)
                    }
                }
                _ => Action::SyntaxError,
            },
            40 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                NEWSECTION => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            41 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                SR => Action::Reduce(2),
                // ExpectedConflicts: ExpectedRRConflicts #(NonAssoc, 0)
                NEWSECTION => Action::Reduce(15),
                _ => Action::SyntaxError,
            },
            42 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                RR => Action::Reduce(2),
                // ExpectedConflicts: ExpectedSRConflicts #(NonAssoc, 0)
                NEWSECTION => Action::Reduce(16),
                _ => Action::SyntaxError,
            },
            43 => match aa_tag {
                NUMBER => Action::Shift(61),
                _ => Action::SyntaxError,
            },
            44 => match aa_tag {
                NUMBER => Action::Shift(61),
                _ => Action::SyntaxError,
            },
            45 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                NEWSECTION => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            46 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                IDENT | AAEnd => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            47 => match aa_tag {
                ERROR => Action::Shift(75),
                ACTION => Action::Shift(70),
                IDENT => Action::Shift(73),
                LITERAL => Action::Shift(74),
                PREDICATE => Action::Shift(71),
                // ProductionTail: <empty> #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(46),
                _ => Action::SyntaxError,
            },
            48 => match aa_tag {
                COLON => Action::Shift(76),
                _ => Action::SyntaxError,
            },
            49 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                IDENT | AAEnd => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            50 => match aa_tag {
                LEFT => Action::Shift(79),
                NONASSOC => Action::Shift(81),
                RIGHT => Action::Shift(80),
                _ => Action::SyntaxError,
            },
            51 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                LEFT | NEWSECTION | NONASSOC | RIGHT | SKIP => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            52 => match aa_tag {
                REGEX => Action::Shift(56),
                _ => Action::SyntaxError,
            },
            53 => match aa_tag {
                // TokenDefinitions: TokenDefinitions OptionalInjection TokenDefinition OptionalInjection #(NonAssoc, 0)
                INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT | SKIP | TOKEN => Action::Reduce(22),
                _ => Action::SyntaxError,
            },
            54 => match aa_tag {
                // TokenDefinition: "%token" NewTokenName LITERAL #(NonAssoc, 0)
                INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT | SKIP | TOKEN => Action::Reduce(23),
                _ => Action::SyntaxError,
            },
            55 => match aa_tag {
                // TokenDefinition: "%token" NewTokenName RegEx #(NonAssoc, 0)
                INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT | SKIP | TOKEN => Action::Reduce(24),
                _ => Action::SyntaxError,
            },
            56 => match aa_tag {
                // RegEx: REGEX #(NonAssoc, 0)
                INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT | SKIP | TOKEN => Action::Reduce(25),
                _ => Action::SyntaxError,
            },
            57 => match aa_tag {
                // Configuration: AttributeType OptionalInjection TargetType OptionalInjection ExpectedConflicts OptionalInjection #(NonAssoc, 0)
                NEWSECTION => Action::Reduce(8),
                _ => Action::SyntaxError,
            },
            58 => match aa_tag {
                SR => Action::Shift(44),
                _ => Action::SyntaxError,
            },
            59 => match aa_tag {
                RR => Action::Shift(43),
                _ => Action::SyntaxError,
            },
            60 => match aa_tag {
                // ExpectedRRConflicts: "%reduce_reduce" Number #(NonAssoc, 0)
                INJECT | NEWSECTION | SR => Action::Reduce(17),
                _ => Action::SyntaxError,
            },
            61 => match aa_tag {
                // Number: NUMBER #(NonAssoc, 0)
                INJECT | NEWSECTION | RR | SR => Action::Reduce(19),
                _ => Action::SyntaxError,
            },
            62 => match aa_tag {
                // ExpectedSRConflicts: "%shift_reduce" Number #(NonAssoc, 0)
                INJECT | NEWSECTION | RR => Action::Reduce(18),
                _ => Action::SyntaxError,
            },
            63 => match aa_tag {
                // Configuration: TargetType OptionalInjection AttributeType OptionalInjection ExpectedConflicts OptionalInjection #(NonAssoc, 0)
                NEWSECTION => Action::Reduce(9),
                _ => Action::SyntaxError,
            },
            64 => match aa_tag {
                // ProductionRules: ProductionRules ProductionGroup OptionalInjection #(NonAssoc, 0)
                IDENT | AAEnd => Action::Reduce(41),
                _ => Action::SyntaxError,
            },
            65 => match aa_tag {
                DOT => Action::Shift(86),
                VBAR => Action::Shift(87),
                _ => Action::SyntaxError,
            },
            66 => match aa_tag {
                // ProductionTailList: ProductionTail #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(44),
                _ => Action::SyntaxError,
            },
            67 => match aa_tag {
                // ProductionTail: Action #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(47),
                _ => Action::SyntaxError,
            },
            68 => match aa_tag {
                ACTION => Action::Shift(70),
                // ProductionTail: Predicate #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(49),
                _ => Action::SyntaxError,
            },
            69 => match aa_tag {
                ERROR => Action::Shift(75),
                PRECEDENCE => Action::Shift(92),
                ACTION => Action::Shift(70),
                IDENT => Action::Shift(73),
                LITERAL => Action::Shift(74),
                PREDICATE => Action::Shift(71),
                // ProductionTail: SymbolList #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(57),
                _ => Action::SyntaxError,
            },
            70 => match aa_tag {
                // Action: ACTION #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(58),
                _ => Action::SyntaxError,
            },
            71 => match aa_tag {
                // Predicate: PREDICATE #(NonAssoc, 0)
                DOT | PRECEDENCE | VBAR | ACTION => Action::Reduce(59),
                _ => Action::SyntaxError,
            },
            72 => match aa_tag {
                // SymbolList: Symbol #(NonAssoc, 0)
                DOT | ERROR | PRECEDENCE | VBAR | ACTION | IDENT | LITERAL | PREDICATE => {
                    Action::Reduce(62)
                }
                _ => Action::SyntaxError,
            },
            73 => match aa_tag {
                // Symbol: IDENT #(NonAssoc, 0)
                DOT | ERROR | PRECEDENCE | VBAR | ACTION | IDENT | LITERAL | PREDICATE => {
                    Action::Reduce(64)
                }
                _ => Action::SyntaxError,
            },
            74 => match aa_tag {
                // Symbol: LITERAL #(NonAssoc, 0)
                DOT | ERROR | PRECEDENCE | VBAR | ACTION | IDENT | LITERAL | PREDICATE => {
                    Action::Reduce(65)
                }
                _ => Action::SyntaxError,
            },
            75 => match aa_tag {
                // Symbol: "%error" #(NonAssoc, 0)
                DOT | ERROR | PRECEDENCE | VBAR | ACTION | IDENT | LITERAL | PREDICATE => {
                    Action::Reduce(66)
                }
                _ => Action::SyntaxError,
            },
            76 => match aa_tag {
                // ProductionGroupHead: IDENT ":" #(NonAssoc, 0)
                DOT | ERROR | VBAR | ACTION | IDENT | LITERAL | PREDICATE => Action::Reduce(43),
                _ => Action::SyntaxError,
            },
            77 => match aa_tag {
                // ProductionRules: OptionalInjection ProductionGroup OptionalInjection #(NonAssoc, 0)
                IDENT | AAEnd => Action::Reduce(40),
                _ => Action::SyntaxError,
            },
            78 => match aa_tag {
                INJECT => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                LEFT | NEWSECTION | NONASSOC | RIGHT => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            79 => match aa_tag {
                IDENT => Action::Shift(98),
                LITERAL => Action::Shift(97),
                _ => Action::SyntaxError,
            },
            80 => match aa_tag {
                IDENT => Action::Shift(98),
                LITERAL => Action::Shift(97),
                _ => Action::SyntaxError,
            },
            81 => match aa_tag {
                IDENT => Action::Shift(98),
                LITERAL => Action::Shift(97),
                _ => Action::SyntaxError,
            },
            82 => match aa_tag {
                // SkipDefinitions: SkipDefinitions OptionalInjection SkipDefinition OptionalInjection #(NonAssoc, 0)
                INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT | SKIP => Action::Reduce(29),
                _ => Action::SyntaxError,
            },
            83 => match aa_tag {
                // SkipDefinition: "%skip" RegEx #(NonAssoc, 0)
                INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT | SKIP => Action::Reduce(30),
                _ => Action::SyntaxError,
            },
            84 => match aa_tag {
                // ExpectedConflicts: ExpectedRRConflicts OptionalInjection ExpectedSRConflicts #(NonAssoc, 0)
                INJECT | NEWSECTION => Action::Reduce(13),
                _ => Action::SyntaxError,
            },
            85 => match aa_tag {
                // ExpectedConflicts: ExpectedSRConflicts OptionalInjection ExpectedRRConflicts #(NonAssoc, 0)
                INJECT | NEWSECTION => Action::Reduce(14),
                _ => Action::SyntaxError,
            },
            86 => match aa_tag {
                // ProductionGroup: ProductionGroupHead ProductionTailList "." #(NonAssoc, 0)
                INJECT | IDENT | AAEnd => Action::Reduce(42),
                _ => Action::SyntaxError,
            },
            87 => match aa_tag {
                ERROR => Action::Shift(75),
                ACTION => Action::Shift(70),
                IDENT => Action::Shift(73),
                LITERAL => Action::Shift(74),
                PREDICATE => Action::Shift(71),
                // ProductionTail: <empty> #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(46),
                _ => Action::SyntaxError,
            },
            88 => match aa_tag {
                // ProductionTail: Predicate Action #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(48),
                _ => Action::SyntaxError,
            },
            89 => match aa_tag {
                PRECEDENCE => Action::Shift(92),
                ACTION => Action::Shift(70),
                // ProductionTail: SymbolList Predicate #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(53),
                _ => Action::SyntaxError,
            },
            90 => match aa_tag {
                ACTION => Action::Shift(70),
                // ProductionTail: SymbolList TaggedPrecedence #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(55),
                _ => Action::SyntaxError,
            },
            91 => match aa_tag {
                // ProductionTail: SymbolList Action #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(56),
                _ => Action::SyntaxError,
            },
            92 => match aa_tag {
                IDENT => Action::Shift(105),
                LITERAL => Action::Shift(106),
                _ => Action::SyntaxError,
            },
            93 => match aa_tag {
                // SymbolList: SymbolList Symbol #(NonAssoc, 0)
                DOT | ERROR | PRECEDENCE | VBAR | ACTION | IDENT | LITERAL | PREDICATE => {
                    Action::Reduce(63)
                }
                _ => Action::SyntaxError,
            },
            94 => match aa_tag {
                // PrecedenceDefinitions: PrecedenceDefinitions OptionalInjection PrecedenceDefinition OptionalInjection #(NonAssoc, 0)
                INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT => Action::Reduce(32),
                _ => Action::SyntaxError,
            },
            95 => match aa_tag {
                IDENT => Action::Shift(98),
                LITERAL => Action::Shift(97),
                // PrecedenceDefinition: "%left" TagList #(NonAssoc, 0)
                INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT => Action::Reduce(33),
                _ => Action::SyntaxError,
            },
            96 => match aa_tag {
                // TagList: Tag #(NonAssoc, 0)
                INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT | IDENT | LITERAL => {
                    Action::Reduce(36)
                }
                _ => Action::SyntaxError,
            },
            97 => match aa_tag {
                // Tag: LITERAL #(NonAssoc, 0)
                INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT | IDENT | LITERAL => {
                    Action::Reduce(38)
                }
                _ => Action::SyntaxError,
            },
            98 => match aa_tag {
                // Tag: IDENT #(NonAssoc, 0)
                INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT | IDENT | LITERAL => {
                    Action::Reduce(39)
                }
                _ => Action::SyntaxError,
            },
            99 => match aa_tag {
                IDENT => Action::Shift(98),
                LITERAL => Action::Shift(97),
                // PrecedenceDefinition: "%right" TagList #(NonAssoc, 0)
                INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT => Action::Reduce(34),
                _ => Action::SyntaxError,
            },
            100 => match aa_tag {
                IDENT => Action::Shift(98),
                LITERAL => Action::Shift(97),
                // PrecedenceDefinition: "%nonassoc" TagList #(NonAssoc, 0)
                INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT => Action::Reduce(35),
                _ => Action::SyntaxError,
            },
            101 => match aa_tag {
                // ProductionTailList: ProductionTailList "|" ProductionTail #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(45),
                _ => Action::SyntaxError,
            },
            102 => match aa_tag {
                ACTION => Action::Shift(70),
                // ProductionTail: SymbolList Predicate TaggedPrecedence #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(51),
                _ => Action::SyntaxError,
            },
            103 => match aa_tag {
                // ProductionTail: SymbolList Predicate Action #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(52),
                _ => Action::SyntaxError,
            },
            104 => match aa_tag {
                // ProductionTail: SymbolList TaggedPrecedence Action #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(54),
                _ => Action::SyntaxError,
            },
            105 => match aa_tag {
                // TaggedPrecedence: "%prec" IDENT #(NonAssoc, 0)
                DOT | VBAR | ACTION => Action::Reduce(60),
                _ => Action::SyntaxError,
            },
            106 => match aa_tag {
                // TaggedPrecedence: "%prec" LITERAL #(NonAssoc, 0)
                DOT | VBAR | ACTION => Action::Reduce(61),
                _ => Action::SyntaxError,
            },
            107 => match aa_tag {
                // TagList: TagList Tag #(NonAssoc, 0)
                INJECT | LEFT | NEWSECTION | NONASSOC | RIGHT | IDENT | LITERAL => {
                    Action::Reduce(37)
                }
                _ => Action::SyntaxError,
            },
            108 => match aa_tag {
                // ProductionTail: SymbolList Predicate TaggedPrecedence Action #(NonAssoc, 0)
                DOT | VBAR => Action::Reduce(50),
                _ => Action::SyntaxError,
            },
            _ => panic!("illegal state: {}", aa_state),
        };
    }

    fn production_data(production_id: u32) -> (AANonTerminal, usize) {
        match production_id {
            0 => (AANonTerminal::AAStart, 1),
            1 => (AANonTerminal::Specification, 6),
            2 => (AANonTerminal::OptionalInjection, 0),
            3 => (AANonTerminal::OptionalInjection, 1),
            4 => (AANonTerminal::InjectionHead, 2),
            5 => (AANonTerminal::Injection, 2),
            6 => (AANonTerminal::Preamble, 0),
            7 => (AANonTerminal::Preamble, 3),
            8 => (AANonTerminal::Configuration, 6),
            9 => (AANonTerminal::Configuration, 6),
            10 => (AANonTerminal::AttributeType, 2),
            11 => (AANonTerminal::TargetType, 2),
            12 => (AANonTerminal::ExpectedConflicts, 0),
            13 => (AANonTerminal::ExpectedConflicts, 3),
            14 => (AANonTerminal::ExpectedConflicts, 3),
            15 => (AANonTerminal::ExpectedConflicts, 1),
            16 => (AANonTerminal::ExpectedConflicts, 1),
            17 => (AANonTerminal::ExpectedRRConflicts, 2),
            18 => (AANonTerminal::ExpectedSRConflicts, 2),
            19 => (AANonTerminal::Number, 1),
            20 => (AANonTerminal::Definitions, 3),
            21 => (AANonTerminal::TokenDefinitions, 2),
            22 => (AANonTerminal::TokenDefinitions, 4),
            23 => (AANonTerminal::TokenDefinition, 3),
            24 => (AANonTerminal::TokenDefinition, 3),
            25 => (AANonTerminal::RegEx, 1),
            26 => (AANonTerminal::NewTokenName, 1),
            27 => (AANonTerminal::NewTokenName, 1),
            28 => (AANonTerminal::SkipDefinitions, 0),
            29 => (AANonTerminal::SkipDefinitions, 4),
            30 => (AANonTerminal::SkipDefinition, 2),
            31 => (AANonTerminal::PrecedenceDefinitions, 0),
            32 => (AANonTerminal::PrecedenceDefinitions, 4),
            33 => (AANonTerminal::PrecedenceDefinition, 2),
            34 => (AANonTerminal::PrecedenceDefinition, 2),
            35 => (AANonTerminal::PrecedenceDefinition, 2),
            36 => (AANonTerminal::TagList, 1),
            37 => (AANonTerminal::TagList, 2),
            38 => (AANonTerminal::Tag, 1),
            39 => (AANonTerminal::Tag, 1),
            40 => (AANonTerminal::ProductionRules, 3),
            41 => (AANonTerminal::ProductionRules, 3),
            42 => (AANonTerminal::ProductionGroup, 3),
            43 => (AANonTerminal::ProductionGroupHead, 2),
            44 => (AANonTerminal::ProductionTailList, 1),
            45 => (AANonTerminal::ProductionTailList, 3),
            46 => (AANonTerminal::ProductionTail, 0),
            47 => (AANonTerminal::ProductionTail, 1),
            48 => (AANonTerminal::ProductionTail, 2),
            49 => (AANonTerminal::ProductionTail, 1),
            50 => (AANonTerminal::ProductionTail, 4),
            51 => (AANonTerminal::ProductionTail, 3),
            52 => (AANonTerminal::ProductionTail, 3),
            53 => (AANonTerminal::ProductionTail, 2),
            54 => (AANonTerminal::ProductionTail, 3),
            55 => (AANonTerminal::ProductionTail, 2),
            56 => (AANonTerminal::ProductionTail, 2),
            57 => (AANonTerminal::ProductionTail, 1),
            58 => (AANonTerminal::Action, 1),
            59 => (AANonTerminal::Predicate, 1),
            60 => (AANonTerminal::TaggedPrecedence, 2),
            61 => (AANonTerminal::TaggedPrecedence, 2),
            62 => (AANonTerminal::SymbolList, 1),
            63 => (AANonTerminal::SymbolList, 2),
            64 => (AANonTerminal::Symbol, 1),
            65 => (AANonTerminal::Symbol, 1),
            66 => (AANonTerminal::Symbol, 1),
            _ => panic!("malformed production data table"),
        }
    }

    fn goto_state(lhs: &AANonTerminal, current_state: u32) -> u32 {
        return match current_state {
            0 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 6,
                AANonTerminal::Preamble => 2,
                AANonTerminal::Specification => 1,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            2 => match lhs {
                AANonTerminal::AttributeType => 8,
                AANonTerminal::Configuration => 7,
                AANonTerminal::TargetType => 9,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            8 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 16,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            9 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 17,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            14 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 20,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            15 => match lhs {
                AANonTerminal::Definitions => 21,
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 23,
                AANonTerminal::TokenDefinitions => 22,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            16 => match lhs {
                AANonTerminal::TargetType => 24,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            17 => match lhs {
                AANonTerminal::AttributeType => 25,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            22 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 28,
                AANonTerminal::SkipDefinitions => 27,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            23 => match lhs {
                AANonTerminal::TokenDefinition => 29,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            24 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 31,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            25 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 32,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            26 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 34,
                AANonTerminal::ProductionRules => 33,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            27 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 36,
                AANonTerminal::PrecedenceDefinitions => 35,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            28 => match lhs {
                AANonTerminal::TokenDefinition => 37,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            30 => match lhs {
                AANonTerminal::NewTokenName => 38,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            31 => match lhs {
                AANonTerminal::ExpectedConflicts => 40,
                AANonTerminal::ExpectedRRConflicts => 41,
                AANonTerminal::ExpectedSRConflicts => 42,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            32 => match lhs {
                AANonTerminal::ExpectedConflicts => 45,
                AANonTerminal::ExpectedRRConflicts => 41,
                AANonTerminal::ExpectedSRConflicts => 42,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            33 => match lhs {
                AANonTerminal::ProductionGroup => 46,
                AANonTerminal::ProductionGroupHead => 47,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            34 => match lhs {
                AANonTerminal::ProductionGroup => 49,
                AANonTerminal::ProductionGroupHead => 47,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            35 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 50,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            36 => match lhs {
                AANonTerminal::SkipDefinition => 51,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            37 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 53,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            38 => match lhs {
                AANonTerminal::RegEx => 55,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            40 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 57,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            41 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 58,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            42 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 59,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            43 => match lhs {
                AANonTerminal::Number => 60,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            44 => match lhs {
                AANonTerminal::Number => 62,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            45 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 63,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            46 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 64,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            47 => match lhs {
                AANonTerminal::Action => 67,
                AANonTerminal::Predicate => 68,
                AANonTerminal::ProductionTail => 66,
                AANonTerminal::ProductionTailList => 65,
                AANonTerminal::Symbol => 72,
                AANonTerminal::SymbolList => 69,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            49 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 77,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            50 => match lhs {
                AANonTerminal::PrecedenceDefinition => 78,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            51 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 82,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            52 => match lhs {
                AANonTerminal::RegEx => 83,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            58 => match lhs {
                AANonTerminal::ExpectedSRConflicts => 84,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            59 => match lhs {
                AANonTerminal::ExpectedRRConflicts => 85,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            68 => match lhs {
                AANonTerminal::Action => 88,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            69 => match lhs {
                AANonTerminal::Action => 91,
                AANonTerminal::Predicate => 89,
                AANonTerminal::Symbol => 93,
                AANonTerminal::TaggedPrecedence => 90,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            78 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 94,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            79 => match lhs {
                AANonTerminal::Tag => 96,
                AANonTerminal::TagList => 95,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            80 => match lhs {
                AANonTerminal::Tag => 96,
                AANonTerminal::TagList => 99,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            81 => match lhs {
                AANonTerminal::Tag => 96,
                AANonTerminal::TagList => 100,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            87 => match lhs {
                AANonTerminal::Action => 67,
                AANonTerminal::Predicate => 68,
                AANonTerminal::ProductionTail => 101,
                AANonTerminal::Symbol => 72,
                AANonTerminal::SymbolList => 69,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            89 => match lhs {
                AANonTerminal::Action => 103,
                AANonTerminal::TaggedPrecedence => 102,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            90 => match lhs {
                AANonTerminal::Action => 104,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            95 => match lhs {
                AANonTerminal::Tag => 107,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            99 => match lhs {
                AANonTerminal::Tag => 107,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            100 => match lhs {
                AANonTerminal::Tag => 107,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            102 => match lhs {
                AANonTerminal::Action => 108,
                _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
            },
            _ => panic!("Malformed goto table: ({}, {})", lhs, current_state),
        };
    }

    fn do_semantic_action<F: FnMut(String, String)>(
        &mut self,
        aa_production_id: u32,
        aa_rhs: Vec<AttributeData>,
        mut aa_inject: F,
    ) -> AttributeData {
        let mut aa_lhs = if let Some(a) = aa_rhs.first() {
            a.clone()
        } else {
            AttributeData::default()
        };
        match aa_production_id {
            2 => {
                // OptionalInjection: <empty> #(NonAssoc, 0)
                // no injection so nothing to do
            }
            4 => {
                // InjectionHead: "%inject" LITERAL #(Right, 1)

                let (text, location) = aa_rhs[1].text_and_location();
                let file_path = text.trim_matches('"');
                match File::open(&file_path) {
                    Ok(mut file) => {
                        let mut text = String::new();
                        if let Err(err) = file.read_to_string(&mut text) {
                            self.error(&location, &format!("Injecting: {}", err));
                        } else if text.len() == 0 {
                            self.error(
                                &location,
                                &format!("Injected file \"{}\" is empty.", file_path),
                            );
                        } else {
                            aa_inject(text, file_path.to_string());
                        }
                    }
                    Err(err) => self.error(&location, &format!("Injecting: {}.", err)),
                };
            }
            6 => {
                // Preamble: <empty> #(NonAssoc, 0)

                // no Preamble defined so there's nothing to do
            }
            7 => {
                // Preamble: OptionalInjection RUSTCODE OptionalInjection #(NonAssoc, 0)

                let text = aa_rhs[1].matched_text();
                self.set_preamble(&text[2..text.len() - 2]);
            }
            10 => {
                // AttributeType: "%attr" IDENT #(NonAssoc, 0)

                self.attribute_type = aa_rhs[1].matched_text().to_string();
            }
            11 => {
                // TargetType: "%target" IDENT #(NonAssoc, 0)

                self.target_type = aa_rhs[1].matched_text().to_string();
            }
            17 => {
                // ExpectedRRConflicts: "%reduce_reduce" Number #(NonAssoc, 0)

                self.expected_rr_conflicts = aa_rhs[1].number();
            }
            18 => {
                // ExpectedSRConflicts: "%shift_reduce" Number #(NonAssoc, 0)

                self.expected_sr_conflicts = aa_rhs[1].number();
            }
            19 => {
                // Number: NUMBER #(NonAssoc, 0)

                match u32::from_str(aa_rhs[0].matched_text()) {
                    Ok(number) => aa_lhs = AttributeData::Number(number),
                    Err(err) => {
                        self.error(aa_rhs[0].location(), &err.to_string());
                        aa_lhs = AttributeData::Number(0);
                    }
                }
            }
            23 => {
                // TokenDefinition: "%token" NewTokenName LITERAL #(NonAssoc, 0)

                let (name, location) = aa_rhs[1].text_and_location();
                let text = aa_rhs[2].matched_text();
                if let Err(err) = self.symbol_table.new_literal_token(name, text, location) {
                    self.error(location, &err.to_string());
                }
            }
            24 => {
                // TokenDefinition: "%token" NewTokenName RegEx #(NonAssoc, 0)

                let (name, location) = aa_rhs[1].text_and_location();
                let text = aa_rhs[2].matched_text();
                if let Err(err) = self.symbol_table.new_regex_token(name, text, location) {
                    self.error(location, &err.to_string());
                }
            }
            25 => {
                // RegEx: REGEX #(NonAssoc, 0)
                let (text, location) = aa_rhs[0].text_and_location();
                if let Err(err) = regex::Regex::new(text) {
                    self.error(
                        location,
                        &format!(
                            "malformed regular expression \"{}\": {}",
                            text,
                            err.to_string()
                        ),
                    );
                }
            }
            26 => {
                // NewTokenName: IDENT #(NonAssoc, 0) ?( !Self::is_allowable_name($1.matched_text()) ?)

                let (name, location) = aa_rhs[0].text_and_location();
                self.warning(
                    location,
                    &format!("token name \"{}\" may clash with generated code", name),
                );
            }
            28 => {
                // SkipDefinitions: <empty> #(NonAssoc, 0)

                // do nothing
            }
            30 => {
                // SkipDefinition: "%skip" RegEx #(NonAssoc, 0)

                let skip_rule = aa_rhs[1].matched_text();
                if let Err(err) = self.symbol_table.add_skip_rule(skip_rule) {
                    self.error(aa_rhs[1].location(), &err.to_string());
                };
            }
            31 => {
                // PrecedenceDefinitions: <empty> #(NonAssoc, 0)

                // do nothing
            }
            33 => {
                // PrecedenceDefinition: "%left" TagList #(NonAssoc, 0)

                let tag_list = aa_rhs[1].tag_or_token_list();
                self.symbol_table
                    .set_precedences(Associativity::Left, tag_list);
            }
            34 => {
                // PrecedenceDefinition: "%right" TagList #(NonAssoc, 0)

                let tag_list = aa_rhs[1].tag_or_token_list();
                self.symbol_table
                    .set_precedences(Associativity::Right, tag_list);
            }
            35 => {
                // PrecedenceDefinition: "%nonassoc" TagList #(NonAssoc, 0)

                let tag_list = aa_rhs[1].tag_or_token_list();
                self.symbol_table
                    .set_precedences(Associativity::NonAssoc, tag_list);
            }
            36 => {
                // TagList: Tag #(NonAssoc, 0)

                let tag_or_token = aa_rhs[0].tag_or_token();
                aa_lhs = AttributeData::TagOrTokenList(vec![tag_or_token.clone()]);
            }
            37 => {
                // TagList: TagList Tag #(NonAssoc, 0)

                let tag_or_token = aa_rhs[1].tag_or_token();
                aa_lhs.tag_or_token_list_mut().push(tag_or_token.clone());
            }
            38 => {
                // Tag: LITERAL #(NonAssoc, 0)

                let lexeme = aa_rhs[0].matched_text();
                if let Some(token) = self.symbol_table.get_literal_token(lexeme) {
                    aa_lhs = AttributeData::TagOrToken(token.into());
                    if token.precedence_has_been_set() {
                        let msg = format!("Token \"{}\" precedence has been set already", lexeme);
                        self.error(aa_rhs[0].location(), &msg);
                    }
                } else {
                    let msg = format!("Literal token \"{}\" is not known", lexeme);
                    self.error(aa_rhs[0].location(), &msg);
                    aa_lhs = AttributeData::TagOrToken(TagOrToken::Invalid);
                }
            }
            39 => {
                // Tag: IDENT #(NonAssoc, 0)

                let name = aa_rhs[0].matched_text();
                if let Some(token) = self.symbol_table.get_token(name) {
                    aa_lhs = AttributeData::TagOrToken(token.into());
                    if token.precedence_has_been_set() {
                        let msg = format!("Token \"{}\" precedence has been set already", name);
                        self.error(aa_rhs[0].location(), &msg);
                    }
                } else {
                    let location = aa_rhs[0].location();
                    if !Self::is_allowable_name(name) {
                        self.warning(
                            location,
                            &format!("tag name \"{}\" may clash with generated code", name),
                        );
                    };
                    match self.symbol_table.new_tag(name, location) {
                        Ok(tag) => aa_lhs = AttributeData::TagOrToken(TagOrToken::from(&tag)),
                        Err(err) => self.error(location, &err.to_string()),
                    }
                }
            }
            42 => {
                // ProductionGroup: ProductionGroupHead ProductionTailList "." #(NonAssoc, 0)

                let lhs = aa_rhs[0].left_hand_side();
                let tails = aa_rhs[1].production_tail_list();
                for tail in tails.iter() {
                    self.new_production(lhs, tail);
                }
            }
            43 => {
                // ProductionGroupHead: IDENT ":" #(NonAssoc, 0)

                let (name, location) = aa_rhs[0].text_and_location();
                match self.symbol_table.non_terminal_defined_at(name, location) {
                    Ok(non_terminal) => {
                        aa_lhs = AttributeData::LeftHandSide(non_terminal);
                    }
                    Err(err) => self.error(location, &err.to_string()),
                }
            }
            44 => {
                // ProductionTailList: ProductionTail #(NonAssoc, 0)

                let production_tail = aa_rhs[0].production_tail().clone();
                aa_lhs = AttributeData::ProductionTailList(vec![production_tail]);
            }
            45 => {
                // ProductionTailList: ProductionTailList "|" ProductionTail #(NonAssoc, 0)

                let production_tail = aa_rhs[2].production_tail();
                aa_lhs
                    .production_tail_list_mut()
                    .push(production_tail.clone());
            }
            46 => {
                // ProductionTail: <empty> #(NonAssoc, 0)

                let tail = ProductionTail::default();
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            47 => {
                // ProductionTail: Action #(NonAssoc, 0)

                let tail = ProductionTail::new(&[], None, None, Some(aa_rhs[0].action()));
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            48 => {
                // ProductionTail: Predicate Action #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    &[],
                    Some(aa_rhs[0].predicate()),
                    None,
                    Some(aa_rhs[1].action()),
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            49 => {
                // ProductionTail: Predicate #(NonAssoc, 0)

                let tail = ProductionTail::new(&[], Some(aa_rhs[0].predicate()), None, None);
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            50 => {
                // ProductionTail: SymbolList Predicate TaggedPrecedence Action #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    aa_rhs[0].symbol_list(),
                    Some(aa_rhs[1].predicate()),
                    Some(aa_rhs[2].associativity_and_precedence()),
                    Some(aa_rhs[3].action()),
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            51 => {
                // ProductionTail: SymbolList Predicate TaggedPrecedence #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    aa_rhs[0].symbol_list(),
                    Some(aa_rhs[1].predicate()),
                    Some(aa_rhs[2].associativity_and_precedence()),
                    None,
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            52 => {
                // ProductionTail: SymbolList Predicate Action #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    aa_rhs[0].symbol_list(),
                    Some(aa_rhs[1].predicate()),
                    None,
                    Some(aa_rhs[2].action()),
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            53 => {
                // ProductionTail: SymbolList Predicate #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    aa_rhs[0].symbol_list(),
                    Some(aa_rhs[1].predicate()),
                    None,
                    None,
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            54 => {
                // ProductionTail: SymbolList TaggedPrecedence Action #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    aa_rhs[0].symbol_list(),
                    None,
                    Some(aa_rhs[1].associativity_and_precedence()),
                    Some(aa_rhs[2].action()),
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            55 => {
                // ProductionTail: SymbolList TaggedPrecedence #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    aa_rhs[0].symbol_list(),
                    None,
                    Some(aa_rhs[1].associativity_and_precedence()),
                    None,
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            56 => {
                // ProductionTail: SymbolList Action #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    aa_rhs[0].symbol_list(),
                    None,
                    None,
                    Some(aa_rhs[1].action()),
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            57 => {
                // ProductionTail: SymbolList #(NonAssoc, 0)

                let tail = ProductionTail::new(aa_rhs[0].symbol_list(), None, None, None);
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            58 => {
                // Action: ACTION #(NonAssoc, 0)

                let text = aa_rhs[0].matched_text();
                aa_lhs = AttributeData::Action(text[2..text.len() - 2].to_string());
            }
            59 => {
                // Predicate: PREDICATE #(NonAssoc, 0)

                let text = aa_rhs[0].matched_text();
                aa_lhs = AttributeData::Predicate(text[2..text.len() - 2].to_string());
            }
            60 => {
                // TaggedPrecedence: "%prec" IDENT #(NonAssoc, 0)

                let (name, location) = aa_rhs[1].text_and_location();
                if let Some(tag) = self.symbol_table.get_tag(name) {
                    tag.add_used_at(location);
                    aa_lhs = AttributeData::AssociativityAndPrecedence(
                        tag.associativity(),
                        tag.precedence(),
                    );
                } else if let Some(token) = self.symbol_table.get_token(name) {
                    aa_lhs = AttributeData::AssociativityAndPrecedence(
                        token.associativity(),
                        token.precedence(),
                    );
                } else {
                    self.error(location, &format!("{}: unknown tag", name));
                    aa_lhs = AttributeData::AssociativityAndPrecedence(Associativity::default(), 0);
                };
            }
            61 => {
                // TaggedPrecedence: "%prec" LITERAL #(NonAssoc, 0)

                let (lexeme, location) = aa_rhs[1].text_and_location();
                if let Some(token) = self.symbol_table.get_literal_token(lexeme) {
                    aa_lhs = AttributeData::AssociativityAndPrecedence(
                        token.associativity(),
                        token.precedence(),
                    );
                } else {
                    self.error(location, &format!("{}: unknown tag", lexeme));
                    aa_lhs = AttributeData::AssociativityAndPrecedence(Associativity::default(), 0);
                };
            }
            62 => {
                // SymbolList: Symbol #(NonAssoc, 0)

                let symbol = aa_rhs[0].symbol();
                aa_lhs = AttributeData::SymbolList(vec![symbol.clone()]);
            }
            63 => {
                // SymbolList: SymbolList Symbol #(NonAssoc, 0)

                let symbol = aa_rhs[1].symbol();
                aa_lhs.symbol_list_mut().push(symbol.clone());
            }
            64 => {
                // Symbol: IDENT #(NonAssoc, 0)

                let (name, location) = aa_rhs[0].text_and_location();
                let symbol = self.symbol_table.symbol_used_at(name, location);
                aa_lhs = AttributeData::Symbol(symbol);
            }
            65 => {
                // Symbol: LITERAL #(NonAssoc, 0)

                let (lexeme, location) = aa_rhs[0].text_and_location();
                if let Some(token) = self.symbol_table.get_literal_token(lexeme) {
                    token.add_used_at(location);
                    aa_lhs = AttributeData::Symbol(token.into());
                } else {
                    self.error(location, &format!("{}: unknown literal)", lexeme));
                    let symbol = self.symbol_table.error_symbol_used_at(location);
                    aa_lhs = AttributeData::Symbol(symbol);
                }
            }
            66 => {
                // Symbol: "%error" #(NonAssoc, 0)

                let location = aa_rhs[0].location();
                let symbol = self.symbol_table.error_symbol_used_at(location);
                aa_lhs = AttributeData::Symbol(symbol);
            }
            _ => aa_inject(String::new(), String::new()),
        };
        aa_lhs
    }
}
