// generated by alap_gen.

use std::{fs::File, io::Read, str::FromStr};

use crate::{
    attributes::*, grammar::Specification, production::ProductionTail, symbol::tag::TagOrToken,
    symbol::Associativity,
};
use std::collections::BTreeSet;

macro_rules! btree_set {
    () => { BTreeSet::new() };
    ( $( $x:expr ),* ) => {
        {
            let mut set = BTreeSet::new();
            $( set.insert($x); )*
            set
        }
    };
    ( $( $x:expr ),+ , ) => {
        btree_set![ $( $x ), * ]
    };
}

#[derive(Debug, Clone, Copy, PartialOrd, Ord, PartialEq, Eq)]
pub enum AATerminal {
    AAEnd,
    ActionCode,
    Attr,
    Colon,
    Dot,
    Error,
    Ident,
    Inject,
    Left,
    Literal,
    NewSection,
    NonAssoc,
    NumberExpr,
    Precedence,
    PredicateExpr,
    ReduceReduce,
    RegEx,
    Right,
    RustCode,
    ShiftReduce,
    Skip,
    Target,
    Token,
    VerticalBar,
}

impl std::fmt::Display for AATerminal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            AATerminal::AAEnd => write!(f, r###"AAEnd"###),
            AATerminal::ActionCode => write!(f, r###"ActionCode"###),
            AATerminal::Attr => write!(f, r###""%attr""###),
            AATerminal::Colon => write!(f, r###"":""###),
            AATerminal::Dot => write!(f, r###"".""###),
            AATerminal::Error => write!(f, r###""%error""###),
            AATerminal::Ident => write!(f, r###"Ident"###),
            AATerminal::Inject => write!(f, r###""%inject""###),
            AATerminal::Left => write!(f, r###""%left""###),
            AATerminal::Literal => write!(f, r###"Literal"###),
            AATerminal::NewSection => write!(f, r###""%%""###),
            AATerminal::NonAssoc => write!(f, r###""%nonassoc""###),
            AATerminal::NumberExpr => write!(f, r###"NumberExpr"###),
            AATerminal::Precedence => write!(f, r###""%prec""###),
            AATerminal::PredicateExpr => write!(f, r###"PredicateExpr"###),
            AATerminal::ReduceReduce => write!(f, r###""%reduce_reduce""###),
            AATerminal::RegEx => write!(f, r###"RegEx"###),
            AATerminal::Right => write!(f, r###""%right""###),
            AATerminal::RustCode => write!(f, r###"RustCode"###),
            AATerminal::ShiftReduce => write!(f, r###""%shift_reduce""###),
            AATerminal::Skip => write!(f, r###""%skip""###),
            AATerminal::Target => write!(f, r###""%target""###),
            AATerminal::Token => write!(f, r###""%token""###),
            AATerminal::VerticalBar => write!(f, r###""|""###),
        }
    }
}

lazy_static::lazy_static! {
    static ref AALEXAN: lexan::LexicalAnalyzer<AATerminal> = {
        use AATerminal::*;
        lexan::LexicalAnalyzer::new(
            &[
                (NewSection, r###"%%"###),
                (Attr, r###"%attr"###),
                (Error, r###"%error"###),
                (Inject, r###"%inject"###),
                (Left, r###"%left"###),
                (NonAssoc, r###"%nonassoc"###),
                (Precedence, r###"%prec"###),
                (ReduceReduce, r###"%reduce_reduce"###),
                (Right, r###"%right"###),
                (ShiftReduce, r###"%shift_reduce"###),
                (Skip, r###"%skip"###),
                (Target, r###"%target"###),
                (Token, r###"%token"###),
                (Dot, r###"."###),
                (Colon, r###":"###),
                (VerticalBar, r###"|"###),
            ],
            &[
                (ActionCode, r###"(!\{(.|[\n\r])*?!\})"###),
                (Literal, r###"("(\\"|[^"\t\r\n\v\f])*")"###),
                (RustCode, r###"(%\{(.|[\n\r])*?%\})"###),
                (NumberExpr, r###"([0-9]+)"###),
                (Ident, r###"([a-zA-Z]+[a-zA-Z0-9_]*)"###),
                (RegEx, r###"(\(.+\))"###),
                (PredicateExpr, r###"(\?\((.|[\n\r])*?\?\))"###),
            ],
            &[
                r###"(/\*(.|[\n\r])*?\*/)"###,
                r###"(//[^\n\r]*)"###,
                r###"(\s+)"###,
            ],
            AAEnd,
        )
    };
}

#[derive(Debug, Clone, Copy, PartialOrd, Ord, PartialEq, Eq)]
pub enum AANonTerminal {
    AAStart,
    Action,
    AttributeType,
    Configuration,
    Definitions,
    ExpectedConflicts,
    ExpectedRRConflicts,
    ExpectedSRConflicts,
    Injection,
    InjectionHead,
    NewTokenName,
    Number,
    OptionalInjection,
    Preamble,
    PrecedenceDefinition,
    PrecedenceDefinitions,
    Predicate,
    ProductionGroup,
    ProductionGroupHead,
    ProductionRules,
    ProductionTail,
    ProductionTailList,
    RegularExpression,
    SkipDefinition,
    SkipDefinitions,
    Specification,
    Symbol,
    SymbolList,
    Tag,
    TagList,
    TaggedPrecedence,
    TargetType,
    TokenDefinition,
    TokenDefinitions,
}

impl std::fmt::Display for AANonTerminal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            AANonTerminal::AAStart => write!(f, r"AAStart"),
            AANonTerminal::Action => write!(f, r"Action"),
            AANonTerminal::AttributeType => write!(f, r"AttributeType"),
            AANonTerminal::Configuration => write!(f, r"Configuration"),
            AANonTerminal::Definitions => write!(f, r"Definitions"),
            AANonTerminal::ExpectedConflicts => write!(f, r"ExpectedConflicts"),
            AANonTerminal::ExpectedRRConflicts => write!(f, r"ExpectedRRConflicts"),
            AANonTerminal::ExpectedSRConflicts => write!(f, r"ExpectedSRConflicts"),
            AANonTerminal::Injection => write!(f, r"Injection"),
            AANonTerminal::InjectionHead => write!(f, r"InjectionHead"),
            AANonTerminal::NewTokenName => write!(f, r"NewTokenName"),
            AANonTerminal::Number => write!(f, r"Number"),
            AANonTerminal::OptionalInjection => write!(f, r"OptionalInjection"),
            AANonTerminal::Preamble => write!(f, r"Preamble"),
            AANonTerminal::PrecedenceDefinition => write!(f, r"PrecedenceDefinition"),
            AANonTerminal::PrecedenceDefinitions => write!(f, r"PrecedenceDefinitions"),
            AANonTerminal::Predicate => write!(f, r"Predicate"),
            AANonTerminal::ProductionGroup => write!(f, r"ProductionGroup"),
            AANonTerminal::ProductionGroupHead => write!(f, r"ProductionGroupHead"),
            AANonTerminal::ProductionRules => write!(f, r"ProductionRules"),
            AANonTerminal::ProductionTail => write!(f, r"ProductionTail"),
            AANonTerminal::ProductionTailList => write!(f, r"ProductionTailList"),
            AANonTerminal::RegularExpression => write!(f, r"RegularExpression"),
            AANonTerminal::SkipDefinition => write!(f, r"SkipDefinition"),
            AANonTerminal::SkipDefinitions => write!(f, r"SkipDefinitions"),
            AANonTerminal::Specification => write!(f, r"Specification"),
            AANonTerminal::Symbol => write!(f, r"Symbol"),
            AANonTerminal::SymbolList => write!(f, r"SymbolList"),
            AANonTerminal::Tag => write!(f, r"Tag"),
            AANonTerminal::TagList => write!(f, r"TagList"),
            AANonTerminal::TaggedPrecedence => write!(f, r"TaggedPrecedence"),
            AANonTerminal::TargetType => write!(f, r"TargetType"),
            AANonTerminal::TokenDefinition => write!(f, r"TokenDefinition"),
            AANonTerminal::TokenDefinitions => write!(f, r"TokenDefinitions"),
        }
    }
}

impl lalr1_plus::Parser<AATerminal, AANonTerminal, AttributeData> for Specification {
    fn lexical_analyzer(&self) -> &lexan::LexicalAnalyzer<AATerminal> {
        &AALEXAN
    }

    fn viable_error_recovery_states(_token: &AATerminal) -> BTreeSet<u32> {
        btree_set![]
    }

    fn look_ahead_set(state: u32) -> BTreeSet<AATerminal> {
        use AATerminal::*;
        return match state {
            0 => btree_set![Attr, Inject, Target, RustCode],
            1 => btree_set![AAEnd],
            2 => btree_set![Attr, Target],
            3 => btree_set![
                Attr,
                Inject,
                Left,
                NewSection,
                NonAssoc,
                ReduceReduce,
                Right,
                ShiftReduce,
                Skip,
                Target,
                Token,
                Ident,
                RustCode,
                AAEnd
            ],
            4 => btree_set![Literal],
            5 => btree_set![Dot],
            6 => btree_set![RustCode],
            7 => btree_set![NewSection],
            8 => btree_set![Inject, Target],
            9 => btree_set![Attr, Inject],
            10 => btree_set![Ident],
            11 => btree_set![Ident],
            12 => btree_set![Dot],
            13 => btree_set![
                Attr,
                Inject,
                Left,
                NewSection,
                NonAssoc,
                ReduceReduce,
                Right,
                ShiftReduce,
                Skip,
                Target,
                Token,
                Ident,
                RustCode,
                AAEnd
            ],
            14 => btree_set![Attr, Inject, Target],
            15 => btree_set![Inject, Token],
            16 => btree_set![Target],
            17 => btree_set![Attr],
            18 => btree_set![Inject, NewSection, ReduceReduce, ShiftReduce, Target],
            19 => btree_set![Attr, Inject, NewSection, ReduceReduce, ShiftReduce],
            20 => btree_set![Attr, Target],
            21 => btree_set![NewSection],
            22 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Skip, Token],
            23 => btree_set![Token],
            24 => btree_set![Inject, NewSection, ReduceReduce, ShiftReduce],
            25 => btree_set![Inject, NewSection, ReduceReduce, ShiftReduce],
            26 => btree_set![Inject, Ident],
            27 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Skip],
            28 => btree_set![Token],
            29 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Skip, Token],
            30 => btree_set![Ident],
            31 => btree_set![Inject, NewSection, ReduceReduce, ShiftReduce],
            32 => btree_set![Inject, NewSection, ReduceReduce, ShiftReduce],
            33 => btree_set![Ident, AAEnd],
            34 => btree_set![Ident],
            35 => btree_set![Inject, Left, NewSection, NonAssoc, Right],
            36 => btree_set![Skip],
            37 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Skip, Token],
            38 => btree_set![Literal, RegEx],
            39 => btree_set![Literal, RegEx],
            40 => btree_set![Inject, NewSection],
            41 => btree_set![Inject, NewSection, ShiftReduce],
            42 => btree_set![Inject, NewSection, ReduceReduce],
            43 => btree_set![NumberExpr],
            44 => btree_set![NumberExpr],
            45 => btree_set![Inject, NewSection],
            46 => btree_set![Inject, Ident, AAEnd],
            47 => btree_set![
                Dot,
                Error,
                VerticalBar,
                ActionCode,
                Ident,
                Literal,
                PredicateExpr
            ],
            48 => btree_set![Colon],
            49 => btree_set![Inject, Ident, AAEnd],
            50 => btree_set![Left, NonAssoc, Right],
            51 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Skip],
            52 => btree_set![RegEx],
            53 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Skip, Token],
            54 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Skip, Token],
            55 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Skip, Token],
            56 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Skip, Token],
            57 => btree_set![NewSection],
            58 => btree_set![ShiftReduce],
            59 => btree_set![ReduceReduce],
            60 => btree_set![Inject, NewSection, ShiftReduce],
            61 => btree_set![Inject, NewSection, ReduceReduce, ShiftReduce],
            62 => btree_set![Inject, NewSection, ReduceReduce],
            63 => btree_set![NewSection],
            64 => btree_set![Ident, AAEnd],
            65 => btree_set![Dot, VerticalBar],
            66 => btree_set![Dot, VerticalBar],
            67 => btree_set![Dot, VerticalBar],
            68 => btree_set![Dot, VerticalBar, ActionCode],
            69 => btree_set![
                Dot,
                Error,
                Precedence,
                VerticalBar,
                ActionCode,
                Ident,
                Literal,
                PredicateExpr
            ],
            70 => btree_set![Dot, VerticalBar],
            71 => btree_set![Dot, Precedence, VerticalBar, ActionCode],
            72 => btree_set![
                Dot,
                Error,
                Precedence,
                VerticalBar,
                ActionCode,
                Ident,
                Literal,
                PredicateExpr
            ],
            73 => btree_set![
                Dot,
                Error,
                Precedence,
                VerticalBar,
                ActionCode,
                Ident,
                Literal,
                PredicateExpr
            ],
            74 => btree_set![
                Dot,
                Error,
                Precedence,
                VerticalBar,
                ActionCode,
                Ident,
                Literal,
                PredicateExpr
            ],
            75 => btree_set![
                Dot,
                Error,
                Precedence,
                VerticalBar,
                ActionCode,
                Ident,
                Literal,
                PredicateExpr
            ],
            76 => btree_set![
                Dot,
                Error,
                VerticalBar,
                ActionCode,
                Ident,
                Literal,
                PredicateExpr
            ],
            77 => btree_set![Ident, AAEnd],
            78 => btree_set![Inject, Left, NewSection, NonAssoc, Right],
            79 => btree_set![Ident, Literal],
            80 => btree_set![Ident, Literal],
            81 => btree_set![Ident, Literal],
            82 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Skip],
            83 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Skip],
            84 => btree_set![Inject, NewSection],
            85 => btree_set![Inject, NewSection],
            86 => btree_set![Inject, Ident, AAEnd],
            87 => btree_set![
                Dot,
                Error,
                VerticalBar,
                ActionCode,
                Ident,
                Literal,
                PredicateExpr
            ],
            88 => btree_set![Dot, VerticalBar],
            89 => btree_set![Dot, Precedence, VerticalBar, ActionCode],
            90 => btree_set![Dot, VerticalBar, ActionCode],
            91 => btree_set![Dot, VerticalBar],
            92 => btree_set![Ident, Literal],
            93 => btree_set![
                Dot,
                Error,
                Precedence,
                VerticalBar,
                ActionCode,
                Ident,
                Literal,
                PredicateExpr
            ],
            94 => btree_set![Inject, Left, NewSection, NonAssoc, Right],
            95 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Ident, Literal],
            96 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Ident, Literal],
            97 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Ident, Literal],
            98 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Ident, Literal],
            99 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Ident, Literal],
            100 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Ident, Literal],
            101 => btree_set![Dot, VerticalBar],
            102 => btree_set![Dot, VerticalBar, ActionCode],
            103 => btree_set![Dot, VerticalBar],
            104 => btree_set![Dot, VerticalBar],
            105 => btree_set![Dot, VerticalBar, ActionCode],
            106 => btree_set![Dot, VerticalBar, ActionCode],
            107 => btree_set![Inject, Left, NewSection, NonAssoc, Right, Ident, Literal],
            108 => btree_set![Dot, VerticalBar],
            _ => panic!("illegal state: {state}"),
        };
    }

    fn next_action(
        &self,
        aa_state: u32,
        aa_attributes: &lalr1_plus::ParseStack<AATerminal, AANonTerminal, AttributeData>,
        aa_token: &lexan::Token<AATerminal>,
    ) -> lalr1_plus::Action {
        use lalr1_plus::Action;
        use AATerminal::*;
        let aa_tag = *aa_token.tag();
        return match aa_state {
            0 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                RustCode => Action::Reduce(2),
                // Preamble: <empty> #(NonAssoc, 0)
                Attr | Target => Action::Reduce(6),
                _ => Action::SyntaxError,
            },
            1 => match aa_tag {
                // AAStart: Specification #(NonAssoc, 0)
                AAEnd => Action::Accept,
                _ => Action::SyntaxError,
            },
            2 => match aa_tag {
                Attr => Action::Shift(10),
                Target => Action::Shift(11),
                _ => Action::SyntaxError,
            },
            3 => match aa_tag {
                // OptionalInjection: Injection #(NonAssoc, 0)
                Attr | Inject | Left | NewSection | NonAssoc | ReduceReduce | Right
                | ShiftReduce | Skip | Target | Token | Ident | RustCode | AAEnd => {
                    Action::Reduce(3)
                }
                _ => Action::SyntaxError,
            },
            4 => match aa_tag {
                Literal => Action::Shift(12),
                _ => Action::SyntaxError,
            },
            5 => match aa_tag {
                Dot => Action::Shift(13),
                _ => Action::SyntaxError,
            },
            6 => match aa_tag {
                RustCode => Action::Shift(14),
                _ => Action::SyntaxError,
            },
            7 => match aa_tag {
                NewSection => Action::Shift(15),
                _ => Action::SyntaxError,
            },
            8 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                Target => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            9 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                Attr => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            10 => match aa_tag {
                Ident => Action::Shift(18),
                _ => Action::SyntaxError,
            },
            11 => match aa_tag {
                Ident => Action::Shift(19),
                _ => Action::SyntaxError,
            },
            12 => match aa_tag {
                // InjectionHead: "%inject" Literal #(Right, 1)
                Dot => Action::Reduce(4),
                _ => Action::SyntaxError,
            },
            13 => match aa_tag {
                // Injection: InjectionHead "." #(NonAssoc, 0)
                Attr | Inject | Left | NewSection | NonAssoc | ReduceReduce | Right
                | ShiftReduce | Skip | Target | Token | Ident | RustCode | AAEnd => {
                    Action::Reduce(5)
                }
                _ => Action::SyntaxError,
            },
            14 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                Attr | Target => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            15 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                Token => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            16 => match aa_tag {
                Target => Action::Shift(11),
                _ => Action::SyntaxError,
            },
            17 => match aa_tag {
                Attr => Action::Shift(10),
                _ => Action::SyntaxError,
            },
            18 => match aa_tag {
                // AttributeType: "%attr" Ident #(NonAssoc, 0)
                Inject | NewSection | ReduceReduce | ShiftReduce | Target => Action::Reduce(10),
                _ => Action::SyntaxError,
            },
            19 => match aa_tag {
                // TargetType: "%target" Ident #(NonAssoc, 0)
                Attr | Inject | NewSection | ReduceReduce | ShiftReduce => Action::Reduce(11),
                _ => Action::SyntaxError,
            },
            20 => match aa_tag {
                // Preamble: OptionalInjection RustCode OptionalInjection #(NonAssoc, 0)
                Attr | Target => Action::Reduce(7),
                _ => Action::SyntaxError,
            },
            21 => match aa_tag {
                NewSection => Action::Shift(26),
                _ => Action::SyntaxError,
            },
            22 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                Token => Action::Reduce(2),
                // SkipDefinitions: <empty> #(NonAssoc, 0)
                Left | NewSection | NonAssoc | Right | Skip => Action::Reduce(28),
                _ => Action::SyntaxError,
            },
            23 => match aa_tag {
                Token => Action::Shift(30),
                _ => Action::SyntaxError,
            },
            24 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                NewSection | ReduceReduce | ShiftReduce => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            25 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                NewSection | ReduceReduce | ShiftReduce => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            26 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                Ident => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            27 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                Skip => Action::Reduce(2),
                // PrecedenceDefinitions: <empty> #(NonAssoc, 0)
                Left | NewSection | NonAssoc | Right => Action::Reduce(31),
                _ => Action::SyntaxError,
            },
            28 => match aa_tag {
                Token => Action::Shift(30),
                _ => Action::SyntaxError,
            },
            29 => match aa_tag {
                // TokenDefinitions: OptionalInjection TokenDefinition #(NonAssoc, 0)
                Inject | Left | NewSection | NonAssoc | Right | Skip | Token => Action::Reduce(21),
                _ => Action::SyntaxError,
            },
            30 => match aa_tag {
                Ident => Action::Shift(39),
                _ => Action::SyntaxError,
            },
            31 => match aa_tag {
                ReduceReduce => Action::Shift(43),
                ShiftReduce => Action::Shift(44),
                // ExpectedConflicts: <empty> #(NonAssoc, 0)
                Inject | NewSection => Action::Reduce(12),
                _ => Action::SyntaxError,
            },
            32 => match aa_tag {
                ReduceReduce => Action::Shift(43),
                ShiftReduce => Action::Shift(44),
                // ExpectedConflicts: <empty> #(NonAssoc, 0)
                Inject | NewSection => Action::Reduce(12),
                _ => Action::SyntaxError,
            },
            33 => match aa_tag {
                Ident => Action::Shift(48),
                // Specification: Preamble Configuration "%%" Definitions "%%" ProductionRules #(NonAssoc, 0)
                AAEnd => Action::Reduce(1),
                _ => Action::SyntaxError,
            },
            34 => match aa_tag {
                Ident => Action::Shift(48),
                _ => Action::SyntaxError,
            },
            35 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                Left | NonAssoc | Right => Action::Reduce(2),
                // Definitions: TokenDefinitions SkipDefinitions PrecedenceDefinitions #(NonAssoc, 0)
                NewSection => Action::Reduce(20),
                _ => Action::SyntaxError,
            },
            36 => match aa_tag {
                Skip => Action::Shift(52),
                _ => Action::SyntaxError,
            },
            37 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                Left | NewSection | NonAssoc | Right | Skip | Token => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            38 => match aa_tag {
                Literal => Action::Shift(54),
                RegEx => Action::Shift(56),
                _ => Action::SyntaxError,
            },
            39 => match aa_tag {
                Literal | RegEx => {
                    if !Self::is_allowable_name(aa_attributes.at_len_minus_n(1).matched_text()) {
                        // NewTokenName: Ident #(NonAssoc, 0) ?( !Self::is_allowable_name($1.matched_text()) ?)
                        Action::Reduce(26)
                    } else {
                        // NewTokenName: Ident #(NonAssoc, 0)
                        Action::Reduce(27)
                    }
                }
                _ => Action::SyntaxError,
            },
            40 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                NewSection => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            41 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                ShiftReduce => Action::Reduce(2),
                // ExpectedConflicts: ExpectedRRConflicts #(NonAssoc, 0)
                NewSection => Action::Reduce(15),
                _ => Action::SyntaxError,
            },
            42 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                ReduceReduce => Action::Reduce(2),
                // ExpectedConflicts: ExpectedSRConflicts #(NonAssoc, 0)
                NewSection => Action::Reduce(16),
                _ => Action::SyntaxError,
            },
            43 => match aa_tag {
                NumberExpr => Action::Shift(61),
                _ => Action::SyntaxError,
            },
            44 => match aa_tag {
                NumberExpr => Action::Shift(61),
                _ => Action::SyntaxError,
            },
            45 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                NewSection => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            46 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                Ident | AAEnd => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            47 => match aa_tag {
                Error => Action::Shift(75),
                ActionCode => Action::Shift(70),
                Ident => Action::Shift(73),
                Literal => Action::Shift(74),
                PredicateExpr => Action::Shift(71),
                // ProductionTail: <empty> #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(46),
                _ => Action::SyntaxError,
            },
            48 => match aa_tag {
                Colon => Action::Shift(76),
                _ => Action::SyntaxError,
            },
            49 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                Ident | AAEnd => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            50 => match aa_tag {
                Left => Action::Shift(79),
                NonAssoc => Action::Shift(81),
                Right => Action::Shift(80),
                _ => Action::SyntaxError,
            },
            51 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                Left | NewSection | NonAssoc | Right | Skip => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            52 => match aa_tag {
                RegEx => Action::Shift(56),
                _ => Action::SyntaxError,
            },
            53 => match aa_tag {
                // TokenDefinitions: TokenDefinitions OptionalInjection TokenDefinition OptionalInjection #(NonAssoc, 0)
                Inject | Left | NewSection | NonAssoc | Right | Skip | Token => Action::Reduce(22),
                _ => Action::SyntaxError,
            },
            54 => match aa_tag {
                // TokenDefinition: "%token" NewTokenName Literal #(NonAssoc, 0)
                Inject | Left | NewSection | NonAssoc | Right | Skip | Token => Action::Reduce(23),
                _ => Action::SyntaxError,
            },
            55 => match aa_tag {
                // TokenDefinition: "%token" NewTokenName RegularExpression #(NonAssoc, 0)
                Inject | Left | NewSection | NonAssoc | Right | Skip | Token => Action::Reduce(24),
                _ => Action::SyntaxError,
            },
            56 => match aa_tag {
                // RegularExpression: RegEx #(NonAssoc, 0)
                Inject | Left | NewSection | NonAssoc | Right | Skip | Token => Action::Reduce(25),
                _ => Action::SyntaxError,
            },
            57 => match aa_tag {
                // Configuration: AttributeType OptionalInjection TargetType OptionalInjection ExpectedConflicts OptionalInjection #(NonAssoc, 0)
                NewSection => Action::Reduce(8),
                _ => Action::SyntaxError,
            },
            58 => match aa_tag {
                ShiftReduce => Action::Shift(44),
                _ => Action::SyntaxError,
            },
            59 => match aa_tag {
                ReduceReduce => Action::Shift(43),
                _ => Action::SyntaxError,
            },
            60 => match aa_tag {
                // ExpectedRRConflicts: "%reduce_reduce" Number #(NonAssoc, 0)
                Inject | NewSection | ShiftReduce => Action::Reduce(17),
                _ => Action::SyntaxError,
            },
            61 => match aa_tag {
                // Number: NumberExpr #(NonAssoc, 0)
                Inject | NewSection | ReduceReduce | ShiftReduce => Action::Reduce(19),
                _ => Action::SyntaxError,
            },
            62 => match aa_tag {
                // ExpectedSRConflicts: "%shift_reduce" Number #(NonAssoc, 0)
                Inject | NewSection | ReduceReduce => Action::Reduce(18),
                _ => Action::SyntaxError,
            },
            63 => match aa_tag {
                // Configuration: TargetType OptionalInjection AttributeType OptionalInjection ExpectedConflicts OptionalInjection #(NonAssoc, 0)
                NewSection => Action::Reduce(9),
                _ => Action::SyntaxError,
            },
            64 => match aa_tag {
                // ProductionRules: ProductionRules ProductionGroup OptionalInjection #(NonAssoc, 0)
                Ident | AAEnd => Action::Reduce(41),
                _ => Action::SyntaxError,
            },
            65 => match aa_tag {
                Dot => Action::Shift(86),
                VerticalBar => Action::Shift(87),
                _ => Action::SyntaxError,
            },
            66 => match aa_tag {
                // ProductionTailList: ProductionTail #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(44),
                _ => Action::SyntaxError,
            },
            67 => match aa_tag {
                // ProductionTail: Action #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(47),
                _ => Action::SyntaxError,
            },
            68 => match aa_tag {
                ActionCode => Action::Shift(70),
                // ProductionTail: Predicate #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(49),
                _ => Action::SyntaxError,
            },
            69 => match aa_tag {
                Error => Action::Shift(75),
                Precedence => Action::Shift(92),
                ActionCode => Action::Shift(70),
                Ident => Action::Shift(73),
                Literal => Action::Shift(74),
                PredicateExpr => Action::Shift(71),
                // ProductionTail: SymbolList #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(57),
                _ => Action::SyntaxError,
            },
            70 => match aa_tag {
                // Action: ActionCode #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(58),
                _ => Action::SyntaxError,
            },
            71 => match aa_tag {
                // Predicate: PredicateExpr #(NonAssoc, 0)
                Dot | Precedence | VerticalBar | ActionCode => Action::Reduce(59),
                _ => Action::SyntaxError,
            },
            72 => match aa_tag {
                // SymbolList: Symbol #(NonAssoc, 0)
                Dot | Error | Precedence | VerticalBar | ActionCode | Ident | Literal
                | PredicateExpr => Action::Reduce(62),
                _ => Action::SyntaxError,
            },
            73 => match aa_tag {
                // Symbol: Ident #(NonAssoc, 0)
                Dot | Error | Precedence | VerticalBar | ActionCode | Ident | Literal
                | PredicateExpr => Action::Reduce(64),
                _ => Action::SyntaxError,
            },
            74 => match aa_tag {
                // Symbol: Literal #(NonAssoc, 0)
                Dot | Error | Precedence | VerticalBar | ActionCode | Ident | Literal
                | PredicateExpr => Action::Reduce(65),
                _ => Action::SyntaxError,
            },
            75 => match aa_tag {
                // Symbol: "%error" #(NonAssoc, 0)
                Dot | Error | Precedence | VerticalBar | ActionCode | Ident | Literal
                | PredicateExpr => Action::Reduce(66),
                _ => Action::SyntaxError,
            },
            76 => match aa_tag {
                // ProductionGroupHead: Ident ":" #(NonAssoc, 0)
                Dot | Error | VerticalBar | ActionCode | Ident | Literal | PredicateExpr => {
                    Action::Reduce(43)
                }
                _ => Action::SyntaxError,
            },
            77 => match aa_tag {
                // ProductionRules: OptionalInjection ProductionGroup OptionalInjection #(NonAssoc, 0)
                Ident | AAEnd => Action::Reduce(40),
                _ => Action::SyntaxError,
            },
            78 => match aa_tag {
                Inject => Action::Shift(4),
                // OptionalInjection: <empty> #(NonAssoc, 0)
                Left | NewSection | NonAssoc | Right => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            79 => match aa_tag {
                Ident => Action::Shift(98),
                Literal => Action::Shift(97),
                _ => Action::SyntaxError,
            },
            80 => match aa_tag {
                Ident => Action::Shift(98),
                Literal => Action::Shift(97),
                _ => Action::SyntaxError,
            },
            81 => match aa_tag {
                Ident => Action::Shift(98),
                Literal => Action::Shift(97),
                _ => Action::SyntaxError,
            },
            82 => match aa_tag {
                // SkipDefinitions: SkipDefinitions OptionalInjection SkipDefinition OptionalInjection #(NonAssoc, 0)
                Inject | Left | NewSection | NonAssoc | Right | Skip => Action::Reduce(29),
                _ => Action::SyntaxError,
            },
            83 => match aa_tag {
                // SkipDefinition: "%skip" RegularExpression #(NonAssoc, 0)
                Inject | Left | NewSection | NonAssoc | Right | Skip => Action::Reduce(30),
                _ => Action::SyntaxError,
            },
            84 => match aa_tag {
                // ExpectedConflicts: ExpectedRRConflicts OptionalInjection ExpectedSRConflicts #(NonAssoc, 0)
                Inject | NewSection => Action::Reduce(13),
                _ => Action::SyntaxError,
            },
            85 => match aa_tag {
                // ExpectedConflicts: ExpectedSRConflicts OptionalInjection ExpectedRRConflicts #(NonAssoc, 0)
                Inject | NewSection => Action::Reduce(14),
                _ => Action::SyntaxError,
            },
            86 => match aa_tag {
                // ProductionGroup: ProductionGroupHead ProductionTailList "." #(NonAssoc, 0)
                Inject | Ident | AAEnd => Action::Reduce(42),
                _ => Action::SyntaxError,
            },
            87 => match aa_tag {
                Error => Action::Shift(75),
                ActionCode => Action::Shift(70),
                Ident => Action::Shift(73),
                Literal => Action::Shift(74),
                PredicateExpr => Action::Shift(71),
                // ProductionTail: <empty> #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(46),
                _ => Action::SyntaxError,
            },
            88 => match aa_tag {
                // ProductionTail: Predicate Action #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(48),
                _ => Action::SyntaxError,
            },
            89 => match aa_tag {
                Precedence => Action::Shift(92),
                ActionCode => Action::Shift(70),
                // ProductionTail: SymbolList Predicate #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(53),
                _ => Action::SyntaxError,
            },
            90 => match aa_tag {
                ActionCode => Action::Shift(70),
                // ProductionTail: SymbolList TaggedPrecedence #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(55),
                _ => Action::SyntaxError,
            },
            91 => match aa_tag {
                // ProductionTail: SymbolList Action #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(56),
                _ => Action::SyntaxError,
            },
            92 => match aa_tag {
                Ident => Action::Shift(105),
                Literal => Action::Shift(106),
                _ => Action::SyntaxError,
            },
            93 => match aa_tag {
                // SymbolList: SymbolList Symbol #(NonAssoc, 0)
                Dot | Error | Precedence | VerticalBar | ActionCode | Ident | Literal
                | PredicateExpr => Action::Reduce(63),
                _ => Action::SyntaxError,
            },
            94 => match aa_tag {
                // PrecedenceDefinitions: PrecedenceDefinitions OptionalInjection PrecedenceDefinition OptionalInjection #(NonAssoc, 0)
                Inject | Left | NewSection | NonAssoc | Right => Action::Reduce(32),
                _ => Action::SyntaxError,
            },
            95 => match aa_tag {
                Ident => Action::Shift(98),
                Literal => Action::Shift(97),
                // PrecedenceDefinition: "%left" TagList #(NonAssoc, 0)
                Inject | Left | NewSection | NonAssoc | Right => Action::Reduce(33),
                _ => Action::SyntaxError,
            },
            96 => match aa_tag {
                // TagList: Tag #(NonAssoc, 0)
                Inject | Left | NewSection | NonAssoc | Right | Ident | Literal => {
                    Action::Reduce(36)
                }
                _ => Action::SyntaxError,
            },
            97 => match aa_tag {
                // Tag: Literal #(NonAssoc, 0)
                Inject | Left | NewSection | NonAssoc | Right | Ident | Literal => {
                    Action::Reduce(38)
                }
                _ => Action::SyntaxError,
            },
            98 => match aa_tag {
                // Tag: Ident #(NonAssoc, 0)
                Inject | Left | NewSection | NonAssoc | Right | Ident | Literal => {
                    Action::Reduce(39)
                }
                _ => Action::SyntaxError,
            },
            99 => match aa_tag {
                Ident => Action::Shift(98),
                Literal => Action::Shift(97),
                // PrecedenceDefinition: "%right" TagList #(NonAssoc, 0)
                Inject | Left | NewSection | NonAssoc | Right => Action::Reduce(34),
                _ => Action::SyntaxError,
            },
            100 => match aa_tag {
                Ident => Action::Shift(98),
                Literal => Action::Shift(97),
                // PrecedenceDefinition: "%nonassoc" TagList #(NonAssoc, 0)
                Inject | Left | NewSection | NonAssoc | Right => Action::Reduce(35),
                _ => Action::SyntaxError,
            },
            101 => match aa_tag {
                // ProductionTailList: ProductionTailList "|" ProductionTail #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(45),
                _ => Action::SyntaxError,
            },
            102 => match aa_tag {
                ActionCode => Action::Shift(70),
                // ProductionTail: SymbolList Predicate TaggedPrecedence #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(51),
                _ => Action::SyntaxError,
            },
            103 => match aa_tag {
                // ProductionTail: SymbolList Predicate Action #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(52),
                _ => Action::SyntaxError,
            },
            104 => match aa_tag {
                // ProductionTail: SymbolList TaggedPrecedence Action #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(54),
                _ => Action::SyntaxError,
            },
            105 => match aa_tag {
                // TaggedPrecedence: "%prec" Ident #(NonAssoc, 0)
                Dot | VerticalBar | ActionCode => Action::Reduce(60),
                _ => Action::SyntaxError,
            },
            106 => match aa_tag {
                // TaggedPrecedence: "%prec" Literal #(NonAssoc, 0)
                Dot | VerticalBar | ActionCode => Action::Reduce(61),
                _ => Action::SyntaxError,
            },
            107 => match aa_tag {
                // TagList: TagList Tag #(NonAssoc, 0)
                Inject | Left | NewSection | NonAssoc | Right | Ident | Literal => {
                    Action::Reduce(37)
                }
                _ => Action::SyntaxError,
            },
            108 => match aa_tag {
                // ProductionTail: SymbolList Predicate TaggedPrecedence Action #(NonAssoc, 0)
                Dot | VerticalBar => Action::Reduce(50),
                _ => Action::SyntaxError,
            },
            _ => panic!("illegal state: {aa_state}"),
        };
    }

    fn production_data(production_id: u32) -> (AANonTerminal, usize) {
        match production_id {
            0 => (AANonTerminal::AAStart, 1),
            1 => (AANonTerminal::Specification, 6),
            2 => (AANonTerminal::OptionalInjection, 0),
            3 => (AANonTerminal::OptionalInjection, 1),
            4 => (AANonTerminal::InjectionHead, 2),
            5 => (AANonTerminal::Injection, 2),
            6 => (AANonTerminal::Preamble, 0),
            7 => (AANonTerminal::Preamble, 3),
            8 => (AANonTerminal::Configuration, 6),
            9 => (AANonTerminal::Configuration, 6),
            10 => (AANonTerminal::AttributeType, 2),
            11 => (AANonTerminal::TargetType, 2),
            12 => (AANonTerminal::ExpectedConflicts, 0),
            13 => (AANonTerminal::ExpectedConflicts, 3),
            14 => (AANonTerminal::ExpectedConflicts, 3),
            15 => (AANonTerminal::ExpectedConflicts, 1),
            16 => (AANonTerminal::ExpectedConflicts, 1),
            17 => (AANonTerminal::ExpectedRRConflicts, 2),
            18 => (AANonTerminal::ExpectedSRConflicts, 2),
            19 => (AANonTerminal::Number, 1),
            20 => (AANonTerminal::Definitions, 3),
            21 => (AANonTerminal::TokenDefinitions, 2),
            22 => (AANonTerminal::TokenDefinitions, 4),
            23 => (AANonTerminal::TokenDefinition, 3),
            24 => (AANonTerminal::TokenDefinition, 3),
            25 => (AANonTerminal::RegularExpression, 1),
            26 => (AANonTerminal::NewTokenName, 1),
            27 => (AANonTerminal::NewTokenName, 1),
            28 => (AANonTerminal::SkipDefinitions, 0),
            29 => (AANonTerminal::SkipDefinitions, 4),
            30 => (AANonTerminal::SkipDefinition, 2),
            31 => (AANonTerminal::PrecedenceDefinitions, 0),
            32 => (AANonTerminal::PrecedenceDefinitions, 4),
            33 => (AANonTerminal::PrecedenceDefinition, 2),
            34 => (AANonTerminal::PrecedenceDefinition, 2),
            35 => (AANonTerminal::PrecedenceDefinition, 2),
            36 => (AANonTerminal::TagList, 1),
            37 => (AANonTerminal::TagList, 2),
            38 => (AANonTerminal::Tag, 1),
            39 => (AANonTerminal::Tag, 1),
            40 => (AANonTerminal::ProductionRules, 3),
            41 => (AANonTerminal::ProductionRules, 3),
            42 => (AANonTerminal::ProductionGroup, 3),
            43 => (AANonTerminal::ProductionGroupHead, 2),
            44 => (AANonTerminal::ProductionTailList, 1),
            45 => (AANonTerminal::ProductionTailList, 3),
            46 => (AANonTerminal::ProductionTail, 0),
            47 => (AANonTerminal::ProductionTail, 1),
            48 => (AANonTerminal::ProductionTail, 2),
            49 => (AANonTerminal::ProductionTail, 1),
            50 => (AANonTerminal::ProductionTail, 4),
            51 => (AANonTerminal::ProductionTail, 3),
            52 => (AANonTerminal::ProductionTail, 3),
            53 => (AANonTerminal::ProductionTail, 2),
            54 => (AANonTerminal::ProductionTail, 3),
            55 => (AANonTerminal::ProductionTail, 2),
            56 => (AANonTerminal::ProductionTail, 2),
            57 => (AANonTerminal::ProductionTail, 1),
            58 => (AANonTerminal::Action, 1),
            59 => (AANonTerminal::Predicate, 1),
            60 => (AANonTerminal::TaggedPrecedence, 2),
            61 => (AANonTerminal::TaggedPrecedence, 2),
            62 => (AANonTerminal::SymbolList, 1),
            63 => (AANonTerminal::SymbolList, 2),
            64 => (AANonTerminal::Symbol, 1),
            65 => (AANonTerminal::Symbol, 1),
            66 => (AANonTerminal::Symbol, 1),
            _ => panic!("malformed production data table"),
        }
    }

    fn goto_state(lhs: &AANonTerminal, current_state: u32) -> u32 {
        return match current_state {
            0 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 6,
                AANonTerminal::Preamble => 2,
                AANonTerminal::Specification => 1,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            2 => match lhs {
                AANonTerminal::AttributeType => 8,
                AANonTerminal::Configuration => 7,
                AANonTerminal::TargetType => 9,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            8 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 16,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            9 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 17,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            14 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 20,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            15 => match lhs {
                AANonTerminal::Definitions => 21,
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 23,
                AANonTerminal::TokenDefinitions => 22,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            16 => match lhs {
                AANonTerminal::TargetType => 24,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            17 => match lhs {
                AANonTerminal::AttributeType => 25,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            22 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 28,
                AANonTerminal::SkipDefinitions => 27,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            23 => match lhs {
                AANonTerminal::TokenDefinition => 29,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            24 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 31,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            25 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 32,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            26 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 34,
                AANonTerminal::ProductionRules => 33,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            27 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 36,
                AANonTerminal::PrecedenceDefinitions => 35,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            28 => match lhs {
                AANonTerminal::TokenDefinition => 37,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            30 => match lhs {
                AANonTerminal::NewTokenName => 38,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            31 => match lhs {
                AANonTerminal::ExpectedConflicts => 40,
                AANonTerminal::ExpectedRRConflicts => 41,
                AANonTerminal::ExpectedSRConflicts => 42,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            32 => match lhs {
                AANonTerminal::ExpectedConflicts => 45,
                AANonTerminal::ExpectedRRConflicts => 41,
                AANonTerminal::ExpectedSRConflicts => 42,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            33 => match lhs {
                AANonTerminal::ProductionGroup => 46,
                AANonTerminal::ProductionGroupHead => 47,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            34 => match lhs {
                AANonTerminal::ProductionGroup => 49,
                AANonTerminal::ProductionGroupHead => 47,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            35 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 50,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            36 => match lhs {
                AANonTerminal::SkipDefinition => 51,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            37 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 53,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            38 => match lhs {
                AANonTerminal::RegularExpression => 55,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            40 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 57,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            41 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 58,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            42 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 59,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            43 => match lhs {
                AANonTerminal::Number => 60,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            44 => match lhs {
                AANonTerminal::Number => 62,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            45 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 63,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            46 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 64,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            47 => match lhs {
                AANonTerminal::Action => 67,
                AANonTerminal::Predicate => 68,
                AANonTerminal::ProductionTail => 66,
                AANonTerminal::ProductionTailList => 65,
                AANonTerminal::Symbol => 72,
                AANonTerminal::SymbolList => 69,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            49 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 77,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            50 => match lhs {
                AANonTerminal::PrecedenceDefinition => 78,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            51 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 82,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            52 => match lhs {
                AANonTerminal::RegularExpression => 83,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            58 => match lhs {
                AANonTerminal::ExpectedSRConflicts => 84,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            59 => match lhs {
                AANonTerminal::ExpectedRRConflicts => 85,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            68 => match lhs {
                AANonTerminal::Action => 88,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            69 => match lhs {
                AANonTerminal::Action => 91,
                AANonTerminal::Predicate => 89,
                AANonTerminal::Symbol => 93,
                AANonTerminal::TaggedPrecedence => 90,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            78 => match lhs {
                AANonTerminal::Injection => 3,
                AANonTerminal::InjectionHead => 5,
                AANonTerminal::OptionalInjection => 94,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            79 => match lhs {
                AANonTerminal::Tag => 96,
                AANonTerminal::TagList => 95,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            80 => match lhs {
                AANonTerminal::Tag => 96,
                AANonTerminal::TagList => 99,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            81 => match lhs {
                AANonTerminal::Tag => 96,
                AANonTerminal::TagList => 100,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            87 => match lhs {
                AANonTerminal::Action => 67,
                AANonTerminal::Predicate => 68,
                AANonTerminal::ProductionTail => 101,
                AANonTerminal::Symbol => 72,
                AANonTerminal::SymbolList => 69,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            89 => match lhs {
                AANonTerminal::Action => 103,
                AANonTerminal::TaggedPrecedence => 102,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            90 => match lhs {
                AANonTerminal::Action => 104,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            95 => match lhs {
                AANonTerminal::Tag => 107,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            99 => match lhs {
                AANonTerminal::Tag => 107,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            100 => match lhs {
                AANonTerminal::Tag => 107,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            102 => match lhs {
                AANonTerminal::Action => 108,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
        };
    }

    fn do_semantic_action<F: FnMut(String, String)>(
        &mut self,
        aa_production_id: u32,
        aa_rhs: Vec<AttributeData>,
        mut aa_inject: F,
    ) -> AttributeData {
        let mut aa_lhs = if let Some(a) = aa_rhs.first() {
            a.clone()
        } else {
            AttributeData::default()
        };
        match aa_production_id {
            2 => {
                // OptionalInjection: <empty> #(NonAssoc, 0)
                // no injection so nothing to do
            }
            4 => {
                // InjectionHead: "%inject" Literal #(Right, 1)

                let (text, location) = aa_rhs[1].text_and_location();
                let file_path = text.trim_matches('"');
                match File::open(file_path) {
                    Ok(mut file) => {
                        let mut text = String::new();
                        if let Err(err) = file.read_to_string(&mut text) {
                            self.error(location, &format!("Injecting: {err}"));
                        } else if text.is_empty() {
                            self.error(
                                location,
                                &format!("Injected file \"{file_path}\" is empty."),
                            );
                        } else {
                            aa_inject(text, file_path.to_string());
                        }
                    }
                    Err(err) => self.error(location, &format!("Injecting: {err}.")),
                };
            }
            6 => {
                // Preamble: <empty> #(NonAssoc, 0)

                // no Preamble defined so there's nothing to do
            }
            7 => {
                // Preamble: OptionalInjection RustCode OptionalInjection #(NonAssoc, 0)

                let text = aa_rhs[1].matched_text();
                self.set_preamble(&text[2..text.len() - 2]);
            }
            10 => {
                // AttributeType: "%attr" Ident #(NonAssoc, 0)

                self.attribute_type = aa_rhs[1].matched_text().to_string();
            }
            11 => {
                // TargetType: "%target" Ident #(NonAssoc, 0)

                self.target_type = aa_rhs[1].matched_text().to_string();
            }
            17 => {
                // ExpectedRRConflicts: "%reduce_reduce" Number #(NonAssoc, 0)

                self.expected_rr_conflicts = aa_rhs[1].number();
            }
            18 => {
                // ExpectedSRConflicts: "%shift_reduce" Number #(NonAssoc, 0)

                self.expected_sr_conflicts = aa_rhs[1].number();
            }
            19 => {
                // Number: NumberExpr #(NonAssoc, 0)

                match u32::from_str(aa_rhs[0].matched_text()) {
                    Ok(number) => aa_lhs = AttributeData::Number(number),
                    Err(err) => {
                        self.error(aa_rhs[0].location(), &err.to_string());
                        aa_lhs = AttributeData::Number(0);
                    }
                }
            }
            23 => {
                // TokenDefinition: "%token" NewTokenName Literal #(NonAssoc, 0)

                let (name, location) = aa_rhs[1].text_and_location();
                let text = aa_rhs[2].matched_text();
                if let Err(err) = self.symbol_table.new_literal_token(name, text, location) {
                    self.error(location, &err.to_string());
                }
            }
            24 => {
                // TokenDefinition: "%token" NewTokenName RegularExpression #(NonAssoc, 0)

                let (name, location) = aa_rhs[1].text_and_location();
                let text = aa_rhs[2].matched_text();
                if let Err(err) = self.symbol_table.new_regex_token(name, text, location) {
                    self.error(location, &err.to_string());
                }
            }
            25 => {
                // RegularExpression: RegEx #(NonAssoc, 0)
                let (text, location) = aa_rhs[0].text_and_location();
                if let Err(err) = regex::Regex::new(text) {
                    self.error(
                        location,
                        &format!("malformed regular expression \"{text}\": {err}"),
                    );
                }
            }
            26 => {
                // NewTokenName: Ident #(NonAssoc, 0) ?( !Self::is_allowable_name($1.matched_text()) ?)

                let (name, location) = aa_rhs[0].text_and_location();
                self.warning(
                    location,
                    &format!("token name \"{name}\" may clash with generated code"),
                );
            }
            28 => {
                // SkipDefinitions: <empty> #(NonAssoc, 0)

                // do nothing
            }
            30 => {
                // SkipDefinition: "%skip" RegularExpression #(NonAssoc, 0)

                let skip_rule = aa_rhs[1].matched_text();
                if let Err(err) = self.symbol_table.add_skip_rule(skip_rule) {
                    self.error(aa_rhs[1].location(), &err.to_string());
                };
            }
            31 => {
                // PrecedenceDefinitions: <empty> #(NonAssoc, 0)

                // do nothing
            }
            33 => {
                // PrecedenceDefinition: "%left" TagList #(NonAssoc, 0)

                let tag_list = aa_rhs[1].tag_or_token_list();
                self.symbol_table
                    .set_precedences(Associativity::Left, tag_list);
            }
            34 => {
                // PrecedenceDefinition: "%right" TagList #(NonAssoc, 0)

                let tag_list = aa_rhs[1].tag_or_token_list();
                self.symbol_table
                    .set_precedences(Associativity::Right, tag_list);
            }
            35 => {
                // PrecedenceDefinition: "%nonassoc" TagList #(NonAssoc, 0)

                let tag_list = aa_rhs[1].tag_or_token_list();
                self.symbol_table
                    .set_precedences(Associativity::NonAssoc, tag_list);
            }
            36 => {
                // TagList: Tag #(NonAssoc, 0)

                let tag_or_token = aa_rhs[0].tag_or_token();
                aa_lhs = AttributeData::TagOrTokenList(vec![tag_or_token.clone()]);
            }
            37 => {
                // TagList: TagList Tag #(NonAssoc, 0)

                let tag_or_token = aa_rhs[1].tag_or_token();
                aa_lhs.tag_or_token_list_mut().push(tag_or_token.clone());
            }
            38 => {
                // Tag: Literal #(NonAssoc, 0)

                let lexeme = aa_rhs[0].matched_text();
                if let Some(token) = self.symbol_table.get_literal_token(lexeme) {
                    aa_lhs = AttributeData::TagOrToken(token.into());
                    if token.precedence_has_been_set() {
                        let msg = format!("Token \"{lexeme}\" precedence has been set already");
                        self.error(aa_rhs[0].location(), &msg);
                    }
                } else {
                    let msg = format!("Literal token \"{lexeme}\" is not known");
                    self.error(aa_rhs[0].location(), &msg);
                    aa_lhs = AttributeData::TagOrToken(TagOrToken::Invalid);
                }
            }
            39 => {
                // Tag: Ident #(NonAssoc, 0)

                let name = aa_rhs[0].matched_text();
                if let Some(token) = self.symbol_table.get_token(name) {
                    aa_lhs = AttributeData::TagOrToken(token.into());
                    if token.precedence_has_been_set() {
                        let msg = format!("Token \"{name}\" precedence has been set already");
                        self.error(aa_rhs[0].location(), &msg);
                    }
                } else {
                    let location = aa_rhs[0].location();
                    if !Self::is_allowable_name(name) {
                        self.warning(
                            location,
                            &format!("tag name \"{name}\" may clash with generated code"),
                        );
                    };
                    match self.symbol_table.new_tag(name, location) {
                        Ok(tag) => aa_lhs = AttributeData::TagOrToken(TagOrToken::from(&tag)),
                        Err(err) => self.error(location, &err.to_string()),
                    }
                }
            }
            42 => {
                // ProductionGroup: ProductionGroupHead ProductionTailList "." #(NonAssoc, 0)

                let lhs = aa_rhs[0].left_hand_side();
                let tails = aa_rhs[1].production_tail_list();
                for tail in tails.iter() {
                    self.new_production(lhs, tail);
                }
            }
            43 => {
                // ProductionGroupHead: Ident ":" #(NonAssoc, 0)

                let (name, location) = aa_rhs[0].text_and_location();
                match self.symbol_table.non_terminal_defined_at(name, location) {
                    Ok(non_terminal) => {
                        aa_lhs = AttributeData::LeftHandSide(non_terminal);
                    }
                    Err(err) => self.error(location, &err.to_string()),
                }
            }
            44 => {
                // ProductionTailList: ProductionTail #(NonAssoc, 0)

                let production_tail = aa_rhs[0].production_tail().clone();
                aa_lhs = AttributeData::ProductionTailList(vec![production_tail]);
            }
            45 => {
                // ProductionTailList: ProductionTailList "|" ProductionTail #(NonAssoc, 0)

                let production_tail = aa_rhs[2].production_tail();
                aa_lhs
                    .production_tail_list_mut()
                    .push(production_tail.clone());
            }
            46 => {
                // ProductionTail: <empty> #(NonAssoc, 0)

                let tail = ProductionTail::default();
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            47 => {
                // ProductionTail: Action #(NonAssoc, 0)

                let tail = ProductionTail::new(&[], None, None, Some(aa_rhs[0].action()));
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            48 => {
                // ProductionTail: Predicate Action #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    &[],
                    Some(aa_rhs[0].predicate()),
                    None,
                    Some(aa_rhs[1].action()),
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            49 => {
                // ProductionTail: Predicate #(NonAssoc, 0)

                let tail = ProductionTail::new(&[], Some(aa_rhs[0].predicate()), None, None);
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            50 => {
                // ProductionTail: SymbolList Predicate TaggedPrecedence Action #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    aa_rhs[0].symbol_list(),
                    Some(aa_rhs[1].predicate()),
                    Some(aa_rhs[2].associativity_and_precedence()),
                    Some(aa_rhs[3].action()),
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            51 => {
                // ProductionTail: SymbolList Predicate TaggedPrecedence #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    aa_rhs[0].symbol_list(),
                    Some(aa_rhs[1].predicate()),
                    Some(aa_rhs[2].associativity_and_precedence()),
                    None,
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            52 => {
                // ProductionTail: SymbolList Predicate Action #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    aa_rhs[0].symbol_list(),
                    Some(aa_rhs[1].predicate()),
                    None,
                    Some(aa_rhs[2].action()),
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            53 => {
                // ProductionTail: SymbolList Predicate #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    aa_rhs[0].symbol_list(),
                    Some(aa_rhs[1].predicate()),
                    None,
                    None,
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            54 => {
                // ProductionTail: SymbolList TaggedPrecedence Action #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    aa_rhs[0].symbol_list(),
                    None,
                    Some(aa_rhs[1].associativity_and_precedence()),
                    Some(aa_rhs[2].action()),
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            55 => {
                // ProductionTail: SymbolList TaggedPrecedence #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    aa_rhs[0].symbol_list(),
                    None,
                    Some(aa_rhs[1].associativity_and_precedence()),
                    None,
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            56 => {
                // ProductionTail: SymbolList Action #(NonAssoc, 0)

                let tail = ProductionTail::new(
                    aa_rhs[0].symbol_list(),
                    None,
                    None,
                    Some(aa_rhs[1].action()),
                );
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            57 => {
                // ProductionTail: SymbolList #(NonAssoc, 0)

                let tail = ProductionTail::new(aa_rhs[0].symbol_list(), None, None, None);
                aa_lhs = AttributeData::ProductionTail(tail)
            }
            58 => {
                // Action: ActionCode #(NonAssoc, 0)

                let text = aa_rhs[0].matched_text();
                aa_lhs = AttributeData::Action(text[2..text.len() - 2].to_string());
            }
            59 => {
                // Predicate: PredicateExpr #(NonAssoc, 0)

                let text = aa_rhs[0].matched_text();
                aa_lhs = AttributeData::Predicate(text[2..text.len() - 2].to_string());
            }
            60 => {
                // TaggedPrecedence: "%prec" Ident #(NonAssoc, 0)

                let (name, location) = aa_rhs[1].text_and_location();
                if let Some(tag) = self.symbol_table.get_tag(name) {
                    tag.add_used_at(location);
                    aa_lhs = AttributeData::AssociativityAndPrecedence(
                        tag.associativity(),
                        tag.precedence(),
                    );
                } else if let Some(token) = self.symbol_table.get_token(name) {
                    aa_lhs = AttributeData::AssociativityAndPrecedence(
                        token.associativity(),
                        token.precedence(),
                    );
                } else {
                    self.error(location, &format!("{name}: unknown tag"));
                    aa_lhs = AttributeData::AssociativityAndPrecedence(Associativity::default(), 0);
                };
            }
            61 => {
                // TaggedPrecedence: "%prec" Literal #(NonAssoc, 0)

                let (lexeme, location) = aa_rhs[1].text_and_location();
                if let Some(token) = self.symbol_table.get_literal_token(lexeme) {
                    aa_lhs = AttributeData::AssociativityAndPrecedence(
                        token.associativity(),
                        token.precedence(),
                    );
                } else {
                    self.error(location, &format!("{lexeme}: unknown tag"));
                    aa_lhs = AttributeData::AssociativityAndPrecedence(Associativity::default(), 0);
                };
            }
            62 => {
                // SymbolList: Symbol #(NonAssoc, 0)

                let symbol = aa_rhs[0].symbol();
                aa_lhs = AttributeData::SymbolList(vec![symbol.clone()]);
            }
            63 => {
                // SymbolList: SymbolList Symbol #(NonAssoc, 0)

                let symbol = aa_rhs[1].symbol();
                aa_lhs.symbol_list_mut().push(symbol.clone());
            }
            64 => {
                // Symbol: Ident #(NonAssoc, 0)

                let (name, location) = aa_rhs[0].text_and_location();
                let symbol = self.symbol_table.symbol_used_at(name, location);
                aa_lhs = AttributeData::Symbol(symbol);
            }
            65 => {
                // Symbol: Literal #(NonAssoc, 0)

                let (lexeme, location) = aa_rhs[0].text_and_location();
                if let Some(token) = self.symbol_table.get_literal_token(lexeme) {
                    token.add_used_at(location);
                    aa_lhs = AttributeData::Symbol(token.into());
                } else {
                    self.error(location, &format!("{lexeme}: unknown literal)"));
                    let symbol = self.symbol_table.error_symbol_used_at(location);
                    aa_lhs = AttributeData::Symbol(symbol);
                }
            }
            66 => {
                // Symbol: "%error" #(NonAssoc, 0)

                let location = aa_rhs[0].location();
                let symbol = self.symbol_table.error_symbol_used_at(location);
                aa_lhs = AttributeData::Symbol(symbol);
            }
            _ => aa_inject(String::new(), String::new()),
        };
        aa_lhs
    }
}
